### ISSUE TITLE
Remove lifetime from `Event`

### ISSUE THREAD

**Issue by oblique** [gakonst/ethers-rs#1014]
**Is your feature request related to a problem? Please describe.**

I'm writing some high-level abstraction that combine multiple contracts in a single struct. In this abstraction I want to use `Event` and store it in an owned struct. However `Event` needs a lifetime because it borrows `self.client` from `Contract`.

**Describe the solution you'd like**

`self.client` of `Contract` is an Arc, so instead of borrowing we can clone it. This will remove lifetime from `Event` struct.

If this is acceptable from you, I can open a PR.

**Comment by mattsse** [comment]
that sounds reasonable, please go for it!

**Comment by gakonst** [comment]
SGTM! Doubt that we're at the point where the Arc vs Lifetime performance is the bottleneck, should always be the RPC so is fine
