### ISSUE TITLE
examples running forever

### ISSUE THREAD

**Issue by gakonst** [gakonst/ethers-rs#1036]
For some reason, Examples keep running without ending. here's an example workflow https://github.com/gakonst/ethers-rs/runs/5553524129?check_suite_focus=true. this is not reproduced locally. the command is basically "run all bins under the examples/ dir" https://github.com/gakonst/ethers-rs/blob/master/scripts/examples.sh. https://github.com/gakonst/ethers-rs/blob/master/.github/workflows/ci.yml#L178

**Comment by mattsse** [comment]
vote close
