### ISSUE TITLE
Deeply nested node_modules remappings auto detection

### ISSUE THREAD

**Issue by mattsse** [gakonst/ethers-rs#1073]
on https://github.com/Uniswap/v3-periphery

`forge remappings` detects

```console
@solidity-parser/=node_modules/solhint/node_modules/@solidity-parser/
```

this is in line with the current rules in place as 

```console
node_modules/solhint/node_modules/@solidity-parser/parser/antlr
└── test.sol
```
is detected as nested submodule in `@solidity-parser`,

I wonder whether we need to fine-tune this, and restrict this to only look up src/node_mules if we're already > 2 dir layers deeper than the last src/node_modules dir
@gakonst

**Comment by gakonst** [comment]
Ah I did not realize there was a test.sol here. Meh, I think this is a `wontfix`, given that it doesn't seem to affect anyone. Good to track, maybe let's revisit if anyone else encounters an edge case in this area.
