### ISSUE TITLE
Error: failed to get `yubihsm` as a dependency of package

### ISSUE THREAD

**Issue by paulrberg** [gakonst/ethers-rs#108]
## Description
I followed the instructions in the [contributing guide](https://github.com/gakonst/ethers-rs/blob/master/CONTRIBUTING.md#cargo-commands) and ran this command:

```sh
cargo build --all-features
```

But I'm getting this error:

```
error: failed to get `yubihsm` as a dependency of package `ethers-signers v0.1.3 (/Users/paulrberg/Workspace/Pad/ethers-rs/ethers-signers)`

Caused by:
  failed to load source for dependency `yubihsm`

Caused by:
  Unable to update https://github.com/iqlusioninc/yubihsm.rs.git?branch=develop#a8fa868f

Caused by:
  object not found - no match for id (a8fa868fbc50b8a326c46ab2b178f42e3e7a4e88); class=Odb (9); code=NotFound (-3)
  ```
  
## Environment

+ macOS@10.15.7
+ git@2.29.2
+ cargo@1.48.0
+ rustc 1.48.0

Plus I have the following setting in my global `.gitconfig`:

```toml
[url "git@github.com:"]
    insteadOf = https://github.com/
	pushInsteadOf = "github:"
	pushInsteadOf = "git://github.com/"
```

To favour SSH over HTTPS.

**Comment by gakonst** [comment]
Thank you for reporting this! This should be fixed in latest master (was fixed in https://github.com/gakonst/ethers-rs/pull/103). Please re-open if the issue persists

**Comment by paulrberg** [comment]
Thanks, it works now! I looked for the Telegram group even before opening the issue. Perhaps worth it to add it to the README?

**Comment by gakonst** [comment]
https://github.com/gakonst/ethers-rs/commit/959b7fe9cea2c3a18f6735b803d996818e68a9f0 done!
