### ISSUE TITLE
Broken EIP-712 support: all `EIP712Domain` fields should be optional

### ISSUE THREAD

**Issue by xJonathanLEI** [gakonst/ethers-rs#1092]
**Version**

N/A

**Platform**

N/A

**Description**

According to [the spec](https://eips.ethereum.org/EIPS/eip-712), all fields in `EIP712Domain` should be optional:

> **Protocol designers only need to include the fields that make sense for their signing domain. Unused fields are left out of the struct type.**

whereas in `ethers-rs` currently only `salt` is:

https://github.com/gakonst/ethers-rs/blob/916e9a73341fab3b326be6ddb6fcd61550c8fc7f/ethers-core/src/types/transaction/eip712.rs#L106-L124

The library pre-computes two type hashes for the domain, but in reality all fields can be optional:

https://github.com/gakonst/ethers-rs/blob/916e9a73341fab3b326be6ddb6fcd61550c8fc7f/ethers-core/src/types/transaction/eip712.rs#L16-L32

**Comment by xJonathanLEI** [comment]
I'm working with the Gnosis Safe contract and it only uses `chainId` and `verifyingContract` for the domain. I can't get it to work without manually implementing `Eip712`.

**Comment by mattsse** [comment]
these are now optional

https://github.com/gakonst/ethers-rs/pull/1510

https://github.com/gakonst/ethers-rs/pull/1485
