### ISSUE TITLE
Inconsistence of TypedTransaction::Eip1559::set_gas_price and get_gas_price

### ISSUE THREAD

**Issue by harpocryptes** [gakonst/ethers-rs#1112]
**Version**
0.6.2

**Description**

In TypedTransaction::Eip1559, set_gas_price and gas_price seem to be inconsistent:
```
	use ethers::types::transaction::eip2718::TypedTransaction;
	let mut tx = TypedTransaction::Eip1559(Eip1559TransactionRequest::new());
	let gas_price = U256::from(1000u64);
	tx.set_gas_price(gas_price);
	assert_eq!(tx.gas_price(), Some(gas_price), "{:#?}", tx);
```
This fails with:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Some(2000)`,
 right: `Some(1000)`: Eip1559(
    Eip1559TransactionRequest {
        from: None,
        to: None,
        gas: None,
        value: None,
        data: None,
        nonce: None,
        access_list: AccessList(
            [],
        ),
        max_priority_fee_per_gas: Some(
            1000,
        ),
        max_fee_per_gas: Some(
            1000,
        ),
    },
)',
```

**Comment by mattsse** [comment]
does this happen on master as well?

because it looks correct here

https://github.com/gakonst/ethers-rs/blob/23e45e85314083fb3e472c1b6a417c37c905f599/ethers-core/src/types/transaction/eip2718.rs#L140-L165

**Comment by harpocryptes** [comment]
Thanks, you're right, this was modified by https://github.com/gakonst/ethers-rs/commit/cde52c7c20c6b2b05f48cb8c8340edd0fa67075c

I still wonder if the logic is correct here:
https://github.com/gakonst/ethers-rs/blob/23e45e85314083fb3e472c1b6a417c37c905f599/ethers-core/src/types/transaction/eip2718.rs#L155-L162

As per https://docs.alchemy.com/alchemy/guides/eip-1559/maxpriorityfeepergas-vs-maxfeepergas:
```maxFeePerGas = baseFeePerGas + maxPriorityFeePerGas```

Is setting both to the same value really the expected behaviour there?

**Comment by meetmangukiya** [comment]
That is so because we do not know the base fee in that call, so both is sent to same gas price effectively making it equivalent to a legacy tx. If you leave it empty, it will fill the base fee from rpc before sending the tx. If you want to set both the base and max fee yourself to different values, you may have to destructure and set the values on `Eip1559TransactionRequest` yourself.

**Comment by harpocryptes** [comment]
Thanks @meetmangukiya, that makes sense. Closing.
