### ISSUE TITLE
[ethers-solc] `pragma experimental` is not stripped on flatten

### ISSUE THREAD

**Issue by pyk** [gakonst/ethers-rs#1115]
**Version**
List the versions of all `ethers-rs` crates you are using. The easiest way to get
this information is using `cargo-tree`.

`cargo install cargo-tree`
(see install here: https://github.com/sfackler/cargo-tree)

Then:

`cargo tree | grep ethers`

```
✦ forge --version
forge 0.2.0 (233ab70 2022-04-01T00:48:24.366564+00:00)
```

I think foundry uses `ethers-rs` on master branch.

**Platform**
The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)

```
✦ uname -a
Darwin pyk-iMac.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:36:53 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T8101 x86_64
```

**Description**
Enter your issue details here.
One way to structure the description:

`pragma experimental` is not stripped on flatten

I tried this code:

```
forge flatten src/Contract.sol > output.sol
```

I expected to see this happen:

`pragma experimental ABIEncoderV2;` will be stripped on each import.

Instead, this happened: 

`pragma experimental ABIEncoderV2;` is not stripped, this issue cause the verify contract on Forge to failed:

```
Error:
   0: Contract verification failed:
      Response: `NOTOK`
      Details: `Fail - Unable to verify`
```

--

https://github.com/gakonst/foundry/issues/852

**Comment by mattsse** [comment]
thanks for this!
so all `pragma experimental ABIEncoderV2;` should be removed or should only a single one be kept?

**Comment by pyk** [comment]
@mattsse I think only the main contract should have the experimental pragma. All imported contracts should be stripped.

I make some PR regarding this #1116 

Let me know what u think! 

Thanks 🙇

**Comment by pyk** [comment]
@mattsse is there any simple way to test this out directly on foundry?

AFAIK `foundryup` only support installing foundry using specific github repo, cannot specify which `ethers-rs` is used.
