### ISSUE TITLE
json-rpc error responses are not handled correctly

### ISSUE THREAD

**Issue by oliver-giersch** [gakonst/ethers-rs#1119]
**Version**
ethers-providers v0.6.2

**Platform**
Linux 5.17.1-arch1-1

**Description**
The `ipc` transport does not handle json-rpc errors in a meaningful way.

https://github.com/gakonst/ethers-rs/blob/6e43d46f5753bcdaf2dead2c2d599d13e43338d1/ethers-providers/src/transports/ipc.rs#L272-L288

In line 276, the received response is converted into a `serde_json::Value` regardless of whether it is a `result` or `error` and sent to the oneshot receiver future at the callsite as is. At the callsite, it is tried to be deserialized into the expected type, e.g. a `H256` when attempting to submit a transaction. This fails, if the tx was, e.g., submitted with too low a nonce, because the rpc error (json) object does not deserialize to a `H256` and you get a very unhelpful straight `serde-json` error with zero additional context.

It would be more sensible, to send a `Result<Value, JsonRpcError>` back to the callsite and handle it appropriately.

**Update**: Checked again, `ws` appears to do it right, by calling `into_result`, not sure why but `ipc` uses `into_value`, which returns `Ok` for both response kinds, unless it is not valid json.

BTW: the entire internal handling of jsonrpc requests looks pretty inefficient as it uses `serde_json::Value` everywhere (basically at least one hashmap), where it could easily be replaced with `serde_json::RawValue`, which is just a string. Basically, the current flow is

```
concrete type -> serde_json::Value -> io-writer
io-reader -> serde_json::Value -> concrete type
```
which constructs a ton of intermediate hashmaps for no real purpose

**Comment by gakonst** [comment]
The IPC connection has been underused historically, so it's possible it's buggy. Thanks for the detailed writeup!

> Update: Checked again, ws appears to do it right, by calling into_result, not sure why but ipc uses into_value, which returns Ok for both response kinds, unless it is not valid json.

Should we do the same there? I'd be supportive of a PR for a fix, happy to help with review/merging
