### ISSUE TITLE
`Contract::connect` should be able to connect to different middleware types

### ISSUE THREAD

**Issue by prestwich** [gakonst/ethers-rs#1158]
`Contract::<M>::connect` has this following signature `pub fn connect(&self, client: Arc<M>) -> Self`

This allows the contract to connect to different **instances** of the same provider. Instead it should have signature:

```
pub fn connect<N>(&self, client: Arc<N>) -> Contract<N>
    where
        N: Middleware + Clone
```

This would allow contracts to change provider types when calling connect.

proposed impl:
```
#[must_use]
    pub fn connect(&self, client: Arc<M>) -> Contract<N>
    where
        M: Clone,
    {
        Contract::<N>::new(self.address, self.base_contract.clone(), client)
    }
```

**Comment by mattsse** [comment]
nice catch!
can add this in a bit

**Comment by prestwich** [comment]
another easy change might be adding `connect` to the output of `abigen` so that it doesn't erase the specialized type of the abigen contract and give you a generic `Contract`

**Comment by prestwich** [comment]
(that's not a big deal as there's a `From` impl but it'd be nice to drop the `into`)
```
// current:
let b: AbigenContract = AbigenContract.connect(new_provider).into();

// desired
let b: AbigenContract = AbigenContract.connect(new_provider);
```

**Comment by mattsse** [comment]
yeh the `connect` is acutally the `Contract::connect` function (because of the deref impl) since the generated type is just a wrapper type.

I guess we can just generate another connect function?
