### ISSUE TITLE
Can't get history logs using provider.subscribe_logs(&filter)

### ISSUE THREAD

**Issue by rusher-R** [gakonst/ethers-rs#1255]
**I can get the latest events after executing the subscription, but even i set the from_block and to_block, i still can't receive history data.

I am confusing.....

And when i use we3.js with same ethereum node, it works well .**

Rust:

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/13580181/168137268-18a5ac94-4a6b-4eaa-a100-17258b4389c5.png">

NodeJS:

<img width="632" alt="截屏2022-05-13 上午1 47 52" src="https://user-images.githubusercontent.com/13580181/168137220-0577240d-a54f-411d-a8cd-b836fef7986b.png">

**Comment by gakonst** [comment]
Dup of https://github.com/gakonst/ethers-rs/issues/988, you need to make a different call for historical events vs subscriptions. We should provide an API that does both, as @mattsse writes in the issue
