### ISSUE TITLE
async usage of `svm-rs`

### ISSUE THREAD

**Issue by rkrasiuk** [gakonst/ethers-rs#1259]
**Is your feature request related to a problem? Please describe.**
usage of `svm-rs` with a `blocking` feature inside a tokio runtime leads to the following error
`Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.`
reqwest::blocking doesn't behave well inside another tokio rt

**Describe the solution you'd like**
use `svm` async threadbound 

cc @mattsse

**Comment by mattsse** [comment]
this is unfortunatelly a limitation of reqwest::blocking

what we could do

1. use svm-async within 

```rust
 runtime::Builder::new_current_thread()
                .enable_io()
                .build().unwrap().block_on(async {svm::install})
```
2. try accessing the Handle or create a new multithreaded rt


actually not sure about the performance benefits of 2 over 1

**Comment by gakonst** [comment]
this is a 2-step process:
1. https://github.com/foundry-rs/foundry/blob/master/utils/src/lib.rs#L27-L54 move this over to ethers-solc (and expose it so we can import it in foundry)
2. Use `RuntimeOrHandle::new().block_on(...)` for the 2 fns where `blocking_install` is called:
    * https://github.com/gakonst/ethers-rs/blob/eb94e53d1f87dc5fe10f25b7268e977cfad24984/ethers-solc/src/resolver/mod.rs#L724
    * https://github.com/gakonst/ethers-rs/blob/eb94e53d1f87dc5fe10f25b7268e977cfad24984/ethers-solc/src/resolver/mod.rs#L742

**Comment by rkrasiuk** [comment]
@gakonst and why don't we `block_on` the actual `svm::blocking_install`?
https://github.com/gakonst/ethers-rs/blob/eb94e53d1f87dc5fe10f25b7268e977cfad24984/ethers-solc/src/compile/mod.rs#L376

**Comment by gakonst** [comment]
I guess that also works :D

**Comment by mattsse** [comment]
vote close @gakonst

**Comment by rkrasiuk** [comment]
second @mattsse. my foundry integration tests seem to be fixed
