### ISSUE TITLE
Document websocket feature in README

### ISSUE THREAD

**Issue by mattsse** [gakonst/ethers-rs#1261]
Similar to legacy section add

* `ws` features
* Note about `rustls` and `openssl`

**Comment by dbelv** [comment]
@mattsse @gakonst 
Please let me know of any comments/issues with https://github.com/gakonst/ethers-rs/pull/1493

Updated the readme to include a providers section documenting websockets and ipc feature-flags. I wasn't sure if there was another idea of where this would go (but figured commenting is easier then creating). 

I took a shot at the note as well in regards to what I presume is https?

**Comment by gakonst** [comment]
That works! Thank you sir.
