### ISSUE TITLE
Expose builder functions in ContractDeployer

### ISSUE THREAD

**Issue by mattsse** [gakonst/ethers-rs#1262]
The `ContractDeployer` helper type is used to deploy contracts

https://github.com/gakonst/ethers-rs/blob/82d5741bcce57901f0a0bee5139ccd57d28e33d8/ethers-contract/src/factory.rs#L24

it is also utilized by `abigen!` for the constructor call, currently it lacks the builder functions the `TransactionRequest` type has. Modifying a deploy tx looks like this rn

```rust
let mut tx =
        Greeter::deploy(Arc::clone(&client), "Hello World!".to_string()).unwrap().deployer.tx;
    tx.set_nonce(nonce);
    tx.set_gas(300_000u64);
```

instead the `ContractDeployer` should have builder functions on par with `TransactionRequest`

ref #1239

**Comment by meetmangukiya** [comment]
@mattse is `Into<TransactionRequest>` better here?

**Comment by gakonst** [comment]
I think we just want functions on `ContractDeployer` so we can do `Greeter::deploy(...).nonce(nonce).gas(gas).send().await?` instead of the syntax Matt wrote above
