### ISSUE TITLE
Add Backoff/Retry functionality to Http Transport

### ISSUE THREAD

**Issue by mattsse** [gakonst/ethers-rs#1291]
we're encountering more and more test failures on foundry due to ratelimited requests that look like

```console
thread 'fork::can_deploy_greeter_on_fork' panicked at 'called `Result::unwrap()` on an `Err` value: JsonRpcClientError(JsonRpcError(JsonRpcError { code: 429, message: "Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemyapi.io/guides/rate-limits", data: None }))', /home/runner/work/foundry/foundry/anvil/src/config.rs:478:57

```

this is alchemyapi https://docs.alchemyapi.io/guides/rate-limits

the request should succeed if we just wait a little, it'd be nice if the Http Provider/Transport had an option to configure this with a backoff interval or something.

@meetmangukiya would this be something you would like to take on?

cc @oliver-giersch

**Comment by meetmangukiya** [comment]
Can look into this next

**Comment by oliver-giersch** [comment]
I think a `RateAwareHttp` or something should be rather easy to realize. I think I'd give it a `min_delay` and (optional) `max_delay` duration and internally keep track of a deadline before sending out any requests. Only ugly part is detecting rate limit errors. The  429 error code looks rather unique, but I bet each provider uses its own code.

**Comment by danielattilasimon** [comment]
I started following this issue because we're also currently being hit by Alchemy rate limits when running Foundry in forking mode.

> Only ugly part is detecting rate limit errors. The 429 error code looks rather unique, but I bet each provider uses its own code.

FWIW status 429 is at least somewhat standard:
https://www.rfc-editor.org/rfc/rfc6585#section-4

In addition to Alchemy, it is also used by Infura to signal being rate limited:
https://docs.infura.io/infura/networks/ethereum/how-to/avoid-rate-limiting#noticing-rate-limiting-behavior

Therefore, IMHO it's not necessarily that ugly to handle 429 by backing off then retrying. If there _is_ a provider out there that doesn't use 429, now _that_ would be really ugly to detect.

**Comment by oliver-giersch** [comment]
Ok, in this case I would propose something simple like the code below.

This is using the #1267 PR I am currently working on and I would just include it in that PR, if that is Ok with everyone.
Normally I would say the deadline mechanism is orthogonal to the retry, but it would be annoying to have to add a timeout to every JSON-RPC request function call, so I think it makes sense to optionally include it in the connection itself.

[Alchemy](https://docs.alchemy.com/alchemy/documentation/throughput#retries) recommends a more complex backoff algorithm, but I think this should do fine.

```rust
/// A rate-limit aware HTTP [`Connection`].
///
/// When this [`Connection`] encounters a rate-limit error, it will wait for a
/// short period of time before trying to send the request again.
/// The wait time inbetween retries increases with each iteration.
#[derive(Debug)]
pub struct DelayedHttp {
    http: Http,
    max_delay: Option<Duration>,
}

impl DelayedHttp {
    // this is the standard error code for rate limit errors and currently used
    // by at least Alchemy & Infura
    // cf. https://www.rfc-editor.org/rfc/rfc6585#section-4
    const RATE_LIMIT_CODE: i64 = 429;
    const INITIAL_BACKOFF: Duration = Duration::from_secs(1);

    /// Creates a new rate-limit aware HTTP [`Connection`] over the given `url`.
    ///
    /// If no `max_delay` is given, the connection will retry indefinitely.
    /// *Note*, that if it is set too short, no retries may ever happen, so it
    /// should be set no lower than at least 2 seconds.
    ///
    /// # Errors
    ///
    /// Fails, if `url` is not a valid URL.
    pub fn new(url: &str, max_delay: Option<Duration>) -> Result<Self, InvalidUrl> {
        let http = Http::new(url)?;
        Ok(Self { http, max_delay })
    }
}

impl Connection for DelayedHttp {
    fn request_id(&self) -> u64 {
        self.http.request_id()
    }

    fn send_raw_request(&self, id: u64, request: String) -> RequestFuture<'_> {
        Box::pin(async move {
            let deadline = self.max_delay.map(|dur| Instant::now() + dur);
            let mut backoff = Self::INITIAL_BACKOFF;

            loop {
                let response = self.http.send_raw_request(id, request.clone()).await;
                match response.as_ref().map_err(|err| err.as_ref()) {
                    Err(TransportError::JsonRpc(err)) if err.code == Self::RATE_LIMIT_CODE => {}
                    _ => return response,
                };

                // if a deadline is set and it is already reached, return the
                // response anyways.
                if let Some(deadline) = deadline {
                    if Instant::now() > deadline {
                        return response;
                    }
                }

                // sleep for the calculated backoff duration
                tokio::time::sleep(backoff).await;
                backoff *= 2;
            }
        })
    }
}
```

**Comment by mattsse** [comment]
that's pretty simple and should work.

@meetmangukiya made some progress here https://github.com/gakonst/ethers-rs/pull/1302

it looks like two parameters influence the backoff behaviour:
* when to retry (code 429 for example)
* what's the next backoff 

so perhaps we should make this configurable

one concern with this `DelayedHttp` is that if we have multiple instances of that we'll always try to send even if we're already rate-limited.
maybe we can optimize this by storing the current backoff in an atomic?

**Comment by gakonst** [comment]
Should we close this given #1302 is merged?
