### ISSUE TITLE
Websockets Not In Scope

### ISSUE THREAD

**Issue by RodrigoVillar** [gakonst/ethers-rs#1314]
**Version**
ethers v0.6.2 (https://github.com/gakonst/ethers-rs#0656ffce)
│   ├── ethers-addressbook v0.1.0 (https://github.com/gakonst/ethers-rs#0656ffce)
│   │   ├── ethers-core v0.6.3 (https://github.com/gakonst/ethers-rs#0656ffce)
│   ├── ethers-contract v0.6.2 (https://github.com/gakonst/ethers-rs#0656ffce)
│   │   ├── ethers-contract-abigen v0.6.3 (https://github.com/gakonst/ethers-rs#0656ffce)
│   │   │   ├── ethers-core v0.6.3 (https://github.com/gakonst/ethers-rs#0656ffce) (*)
│   │   ├── ethers-contract-derive v0.6.3 (proc-macro) (https://github.com/gakonst/ethers-rs#0656ffce)
│   │   │   ├── ethers-contract-abigen v0.6.3 (https://github.com/gakonst/ethers-rs#0656ffce)
│   │   │   │   ├── ethers-core v0.6.3 (https://github.com/gakonst/ethers-rs#0656ffce)
│   │   │   ├── ethers-core v0.6.3 (https://github.com/gakonst/ethers-rs#0656ffce) (*)
│   │   ├── ethers-core v0.6.3 (https://github.com/gakonst/ethers-rs#0656ffce) (*)
│   │   ├── ethers-providers v0.6.2 (https://github.com/gakonst/ethers-rs#0656ffce)
│   │   │   ├── ethers-core v0.6.3 (https://github.com/gakonst/ethers-rs#0656ffce) (*)
│   ├── ethers-core v0.6.3 (https://github.com/gakonst/ethers-rs#0656ffce) (*)
│   ├── ethers-etherscan v0.2.2 (https://github.com/gakonst/ethers-rs#0656ffce)
│   │   ├── ethers-core v0.6.3 (https://github.com/gakonst/ethers-rs#0656ffce) (*)
│   │   ├── ethers-solc v0.3.0 (https://github.com/gakonst/ethers-rs#0656ffce)
│   │   │   ├── ethers-core v0.6.3 (https://github.com/gakonst/ethers-rs#0656ffce) (*)
│   ├── ethers-middleware v0.6.2 (https://github.com/gakonst/ethers-rs#0656ffce)
│   │   ├── ethers-contract v0.6.2 (https://github.com/gakonst/ethers-rs#0656ffce) (*)
│   │   ├── ethers-core v0.6.3 (https://github.com/gakonst/ethers-rs#0656ffce) (*)
│   │   ├── ethers-etherscan v0.2.2 (https://github.com/gakonst/ethers-rs#0656ffce) (*)
│   │   ├── ethers-providers v0.6.2 (https://github.com/gakonst/ethers-rs#0656ffce) (*)
│   │   ├── ethers-signers v0.6.2 (https://github.com/gakonst/ethers-rs#0656ffce)
│   │   │   ├── ethers-core v0.6.3 (https://github.com/gakonst/ethers-rs#0656ffce) (*)
│   ├── ethers-providers v0.6.2 (https://github.com/gakonst/ethers-rs#0656ffce) (*)
│   ├── ethers-signers v0.6.2 (https://github.com/gakonst/ethers-rs#0656ffce) (*)
│   └── ethers-solc v0.3.0 (https://github.com/gakonst/ethers-rs#0656ffce) (*)

**Platform**
Ubuntu 20.04.1 64 Bit
**Description**

Short summary: code will not compile because Websockets cannot be found within the ethers crate

I tried compiling the following code from 'examples/subscribe_logs.rs'. Out of all the compile-time errors I get, the one i'm mainly concerned about is the following:

  `--> src/main.rs:10:20
   |
10 |         Provider::<Ws>::connect("wss://mainnet.infura.io/ws/v3/<INSERT-API-KEY-HERE>")
   |                    ^^ not found in this scope`

I also find this to be an issue for code in `examples/` that utilizes websockets.

**Comment by meetmangukiya** [comment]
run with `--features ws`

**Comment by RodrigoVillar** [comment]
@meetmangukiya thank you, closing issue
