### ISSUE TITLE
Upgrade asymmetric crypto dependencies

### ISSUE THREAD

**Issue by agostbiro** [gakonst/ethers-rs#1390]
**Version**

```
ethers-core v0.13.0
ethers-providers v0.13.0
ethers-signers v0.13.0
```

**Platform**

```
Darwin Agosts-MacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
```

**Description**

I'm trying to use `k256 = ^0.11` in my project, but `ethers-core` currently specifies `k256 = "^0.10.4"`. This gives the following error, because apparently multiple versions of the `signature` crate aren't supported by cargo:

```
error: failed to select a version for `signature`.
    ... required by package `ecdsa v0.13.4`
    ... which satisfies dependency `ecdsa-core = "^0.13"` of package `k256 v0.10.4`
    ... which satisfies dependency `k256 = "^0.10.4"` of package `ethers-core v0.13.0`
    ... which satisfies dependency `ethers-core = "^0.13.0"` of package `ethers-providers v0.13.0`
    ... which satisfies dependency `ethers-providers = "^0.13.0"` of package `seal_vault_core v0.1.0 (/Users/abiro/repos/seal-vault/core)`
    ... which satisfies path dependency `seal_vault_core` (locked to 0.1.0) of package `seal_vault_dev v0.1.0 (/Users/abiro/repos/seal-vault/dev)`
versions that meet the requirements `>=1.3.1, <1.5` are: 1.4.0, 1.3.2, 1.3.1

all possible versions conflict with previously selected packages.

  previously selected package `signature v1.5.0`
    ... which satisfies dependency `signature = "^1.5"` of package `ecdsa v0.14.2`
    ... which satisfies dependency `ecdsa-core = "^0.14"` of package `k256 v0.11.0`
    ... which satisfies dependency `k256 = "^0.11"` of package `seal_vault_core v0.1.0 (/Users/abiro/repos/seal-vault/core)`
    ... which satisfies path dependency `seal_vault_core` (locked to 0.1.0) of package `seal_vault_dev v0.1.0 (/Users/abiro/repos/seal-vault/dev)`

failed to select a version for `signature` which could resolve this conflict
```

I've tried to set `k256 = ^0.11` in `ethers-core`, but some transitive dependencies also rely on an older version of `signature`, so this fails. Specifically, `yubihsm = "0.40.0"` and `coins-bip32 = "0.6.0"` are affected. 

I've submitted a [PR to yubihsm](https://github.com/iqlusioninc/yubihsm.rs/pull/325) to update their dependencies and I've also created a [draft PR for coins-bip32,](https://github.com/summa-tx/bitcoins-rs/pull/97) but latter regrettably fails due to a build error that I haven't been able to resolve (any help there appreciated).

It'd be important to upgrade to `k256 = ^0.11`, because it [shipped](https://github.com/RustCrypto/elliptic-curves/pull/559) out of the box support for RFC6979 deterministic ECDSA `k` values using SHA256 in signatures which would enable removing Sha256Proxy (#966).

**Comment by tarcieri** [comment]
See also [`VerifyPrimitive::verify_prehashed`](https://docs.rs/ecdsa/0.14.2/ecdsa/hazmat/trait.VerifyPrimitive.html#method.verify_prehashed) as a way to verify a signature from a prehashed message digest.

There shouldn't be any need to use the `Reduce` trait directly anymore (at least for ECDSA-related purposes).

**Comment by agostbiro** [comment]
I've verified now that the code below using `k256 = 0.11.2` produces identical signatures to `ethers-signers = 0.13` private key signer:

```rust
use k256::ecdsa::recoverable::Signature as RecoverableSignature;
use k256::ecdsa::signature::DigestSigner;
use k256::ecdsa::SigningKey;
use k256::elliptic_curve::rand_core::OsRng;
use sha3::{Digest, Keccak256};

fn main() {
    let key = SigningKey::random(&mut OsRng);
    let message = "hello world";
    let digest = Keccak256::new_with_prefix(message.as_bytes());
    let _sig: RecoverableSignature = key.try_sign_digest(digest).unwrap();
}

```

**Comment by agostbiro** [comment]
Quick update: The PR to [yubihsm](https://github.com/iqlusioninc/yubihsm.rs/pull/325) is now merged (thanks @tarcieri !), but there are [blockers in bitcoins-rs.](https://github.com/summa-tx/bitcoins-rs/issues/96#issuecomment-1164163453)

**Comment by mattsse** [comment]
ref https://github.com/summa-tx/bitcoins-rs/pull/101

**Comment by mattsse** [comment]
yep, I think we're good and all crypto deps should be based on digest 0.10 now

**Comment by agostbiro** [comment]
great, thanks!
