### ISSUE TITLE
Turn TypedTransaction functions into builder style functions

### ISSUE THREAD

**Issue by mattsse** [gakonst/ethers-rs#1400]
`TypedTransaction` functions like `TypedTransaction::set_value` return nothing.

they either should return `&mut Self` or consume self and return `Self`

if we don't want to break existing functions we should return `&mut Self`

**Comment by h00p30** [comment]
Tell me if I'm wrong but from what I understand you want `TypedTransaction` to be the builder for different types of transaction like in [this](https://rust-unofficial.github.io/patterns/patterns/creational/builder.html), so we can do things like `tx.set_from(addr1).set_to(addr2).set_value(1).build()` ?

**Comment by mattsse** [comment]
landed with #1414
