### ISSUE TITLE
JSON Representation of `CompilerOutput` Incorrect

### ISSUE THREAD

**Issue by tynes** [gakonst/ethers-rs#1422]
**Version**
`forge 0.2.0 (9dcc095 2022-06-28T00:03:46.153858156Z)`

**Platform**
`Linux 5.10.114-1-MANJARO x86_64 GNU/Linux`

**Description**
The `CompilerOutput` JSON that is included in the `BuildInfo` is causing Hardhat to crash because it is serializing the `bytecode` and `deployedBytecode` with a `0x` prefix while `solc` does not prefix those hex strings with `0x` prefixes. This difference causes the conversion from a string to buffer in hardhat to fail and subsequently crash.

If the build info files generated by foundry are present, it will crash hardhat due to this reason.

**Comment by mattsse** [comment]
...
this is so annoying lol

we explicitly added 0x prefixes for artifacts which use the same types as `CompilerOutput`, I'm not sure yet what would be the simplest solution here

**Comment by tynes** [comment]
The `0x` prefix is so standard at this point, if solc updates then it'll break a ton of tooling so idk we might be stuck with things like this
Linking the hh issue here: https://github.com/NomicFoundation/hardhat/issues/2883
