### ISSUE TITLE
solc: handle conflicting <file>/<contract name> pairs properly

### ISSUE THREAD

**Issue by mattsse** [gakonst/ethers-rs#1487]
as highlighted here https://github.com/foundry-rs/foundry/issues/1488

when emitting duplicated file + contract name pairs we end up overwriting them.

This is a scenario I did not anticipate when implementing the output handler and a limitation of the current layout `file/contract-name.sol`

we handle multiple versions with a version suffix in the file name.

if there are multiple file+name pairs it's guaranteed that the file is in another folder, meaning `parent(file)` is always unique. so perhaps if there are conflicts, we add the `parent(file)|project roo` to the output path.

either has `out/parent(file)/file/contract.sol`

**Comment by gakonst** [comment]
I would have expected this to be an anti pattern..agree it's an edge case we hadn't considered. When does this happen?

**Comment by onbjerg** [comment]
Artifacts are in `out/<filename>/<contract>.json`, so if you have something like:

```
src/a/Token.sol
src/b/Token.sol
```

and both of them have a similar named contract, then you'd have a conflict in the `out` directory
