### ISSUE TITLE
Add Solidity Keccak256 packing support

### ISSUE THREAD

**Issue by Ethan-000** [gakonst/ethers-rs#1529]
Hi. Is anyone working on adding Solidity Keccak256 packing support? 

```
/// Compute the Keccak-256 hash of input bytes.
// TODO: Add Solidity Keccak256 packing support
pub fn keccak256<S>(bytes: S) -> [u8; 32]
where
    S: AsRef<[u8]>,
{
    let mut output = [0u8; 32];
    let mut hasher = Keccak::v256();
    hasher.update(bytes.as_ref());
    hasher.finalize(&mut output);
    output
}
```

In ethers-js, its here
https://github.com/ethers-io/ethers.js/blob/master/packages/bytes/src.ts/index.ts.

I don't know rust or the package well enough to add this myself. It could be helpful if someone can do this. Thanks!

**Comment by Ethan-000** [comment]
found the abi.encode and get_create2_address function.

**Comment by Ethan-000** [comment]
eh I think no abi pack util so I'll reopen

**Comment by tynes** [comment]
Do you mean `abi.encodePacked`?

**Comment by Ethan-000** [comment]
yes

**Comment by cbrzn** [comment]
hey just wanted to share that would be awesome if this function is developed :-), if someone would like to deeply interact with safe contracts, they will need this

**Comment by DaniPopes** [comment]
Actually it already is present as `abi::encode_packed`: <https://github.com/gakonst/ethers-rs/blob/master/ethers-core/src/abi/packed.rs>

It just hasn't been released yet

@gakonst we can close this, same as #1862
