### ISSUE TITLE
Update Multicall to Multicall3

### ISSUE THREAD

**Issue by DaniPopes** [gakonst/ethers-rs#1576]
### Problem
[Multicall](https://github.com/makerdao/multicall) supports very few chains and with different contract addresses, as well as always reverting on a single call failure. Another problem is that the `Multicall` struct is only initializable by either having the address beforehand or asynchronously with a call to `get_chain_id`.

### Proposed solution
Upgrading to the [maintained fork Multicall](https://github.com/mds1/multicall). It includes `Multicall3` with a higher chain coverage, always deployed at the same address (`0xcA11bde05977b3631167028862bE2a173976CA11`), retro-compatible and more advanced contract methods (ex. specify `allowFailure` or `value` for each call).

I have already made some changes for my own project and can easily port them over in a PR.

Please let me know what you think about this 😃

**Comment by gakonst** [comment]
SGTM - PR is welcome
