### ISSUE TITLE
EIP712 Support

### ISSUE THREAD

**Issue by gakonst** [gakonst/ethers-rs#16]
**Is your feature request related to a problem? Please describe.**

EIP712 support is missing.

**Describe the solution you'd like**

We should be able to sign messages using EIP712

**Additional context**

There's an open PR for it in Web3js https://github.com/ethereum/web3.js/pull/3449
https://github.com/0xProject/0x-protocol-specification/issues/11

**Comment by fubuloubu** [comment]
Relevant:
https://github.com/tomusdrw/rust-web3/issues/169
https://crates.io/crates/eip-712

**Comment by roynalnaruto** [comment]
Hello @gakonst if you have not worked on this issue, I would like to take it up. The plan is to use the [above mentioned crate](https://crates.io/crates/eip-712).

One more point to note is that, the `Signer` trait currently supports a `sign_message` which eventually hashes the `message`. I would need to add:
```rust
/// Signs the provided message
fn sign_hashed_message<S: AsRef<[u8]>>(&self, message: S) -> Signature;
```
where the `message` argument is already hashed, and hence won't be hashed before signing. This requirement is because the [hash_structured_data](https://docs.rs/eip-712/0.1.1/eip_712/fn.hash_structured_data.html) function already hashes the encoded data.

**Comment by roynalnaruto** [comment]
> I believe that this wouldn't be compatible with the MIT / Apache-2 license. That said, I think we could re-implement that functionality using a custom Serde visitor instead of the parser they use?

Okay, I will go through Serde's docs and try to implement it :)

**Comment by mattsse** [comment]
Any progress on this?
There is now [graphprotocol/eip-712-derive](https://github.com/graphprotocol/eip-712-derive).
The repo contains no license yet, however author [hinted](https://github.com/tomusdrw/rust-web3/issues/169#issuecomment-653108884) that is MIT

**Comment by gakonst** [comment]
Nobody that I know of is working on it, so if you'd like to integrate it, along with an eth sign typed data call I'd be more than happy to merge.

**Comment by gakonst** [comment]
Here's a potentially simpler approach than Graph Protocol's:

1. Define a trait EIP712
2. Define a struct e.g. struct Name { field1: U256; field2: u65 }
3. Have a derive macro which implements the EIP712 trait for that struct

The trait could have a `fn typehash()` which auto generates the typehash from the datatype, similar to [this](https://github.com/gakonst/ethers-rs/commit/46faf7614b6e97b2077ff9d6693b0e28364457c9#diff-0707293bf72a66a870230d5156a29d325f07ba81a57453918ced475f05fa0a52R33) and a `fn input(&self)` which would abi encode each field of the struct, same as [this](https://github.com/gakonst/ethers-rs/commit/46faf7614b6e97b2077ff9d6693b0e28364457c9#diff-0707293bf72a66a870230d5156a29d325f07ba81a57453918ced475f05fa0a52R61-R70)

And then you’d have a `StructName.eip712_encode()` which calculates the full hash by calling:
1. `self.domain_separator()`
2. `self.typehash`
3. calculate input
4. hash them together

We could add an extra param on the derive macro which would set name and version for the domain separator, maybe let verifying_contract and chainid be defined at runtime, since you may want to use the same e.g permit struct for many contracts or many chains (it’d be nice if both could work)

Strawman syntax:

```
#[derive(Debug, EIP712)]
#[eip712(name = “Uniswap V2”, version = “1”, chainId = 1, verifyingContract = “0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc”)]
struct Permit {
    owner: Address,
    spender: Address,
    value: U256,
    nonce: U256,
    deadline: U256,

let permit = Permit { … };
dbg!(permit.typed_hash())
```

It’d basically be very `abigen`-like, and I think I prefer it to the approach that the Graph took.

The trait may not be necessary by default, by I suspect it’d be useful for 3rd party consumers, to be abstract over the data that you want to typehash for (e.g. wallets)

**Comment by Ryanmtate** [comment]
Opened #481 as a draft PR. It's a first iteration and is lacking test coverage against solidity and other libs, such as https://crates.io/crates/eip-712. 

Additionally, the macro currently does not recurse all nested Eip712 structs.

I welcome early feedback on the code and any thoughts on improvements. Once test coverage and nested structs are completed, I'll move the PR from draft status to open.

**Comment by Ryanmtate** [comment]
#481 closes this issue. A new issue should be opened to track nested Eip712 structs and another issue for crate restructuring to re-export the macro.

**Comment by gakonst** [comment]
Issues opened, thank you for the hard work on this.

**Comment by Ryanmtate** [comment]
> Issues opened, thank you for the hard work on this.

No problem! Will keep an eye on those issues and lend a hand where needed! :)
