### ISSUE TITLE
Unavailable to set the chain_id for the wallet

### ISSUE THREAD

**Issue by memekas** [gakonst/ethers-rs#1609]
I create a wallet from keystore using `decrypt_keystore`
https://github.com/gakonst/ethers-rs/blob/92b51b6d9fbec759857a5af01437540bee5edde2/ethers-signers/src/wallet/private_key.rs#L76

And this function creates Wallet with hardcoded `chainID`
https://github.com/gakonst/ethers-rs/blob/92b51b6d9fbec759857a5af01437540bee5edde2/ethers-signers/src/wallet/private_key.rs#L84

I haven't found any other ways to set `chain_id`. Please, add a setter for `chain_id`

**Comment by mattsse** [comment]
there's 

https://docs.rs/ethers/latest/ethers/signers/struct.Wallet.html#method.with_chain_id

which consumes the type, we could add a setter that uses `&mut self` as well

**Comment by gakonst** [comment]
yeah you should do `decrypt_keystore(...)?.with_chain_id(..)`
