### ISSUE TITLE
int256 types not supported by abigen!

### ISSUE THREAD

**Issue by 1saf** [gakonst/ethers-rs#169]
**Version**
`0.2.0`

**Platform**
`Ubuntu 20.04 - WSL2 Environment`

**Description**
Attempting to use abigen! to generate rust bindings for a contract which uses `int256` types. I saw that this was not tokenizable so I refactored all instances of `int256` types to `uint256` types and it correctly ran the macro.

I tried this code:
```js
abigen!(
        Layer2ClearingHouseContract,
        "./src/contracts/abi/ClearingHouse.json"
    );
```
With an ABI JSON file which extensively used the int256 type. I refactored the example abigen! as well to use int256 for `setValue` and that throws an error too.

```js
    abigen!(
        SimpleContract,
        r#"[
            function setValue(int256)
            function getValue() external view (string)
            event ValueChanged(address indexed author, address indexed oldAuthor, string oldValue, string newValue)
        ]"#,
        event_derives(serde::Deserialize, serde::Serialize)
    );
```

Refactoring to uint256 works as well, but I am not sure if it has any implications to the contract. I would love to help contribute but I am literally a newborn baby to the world of Rust and tried to navigate the ethers-rs source code...but I got as far as abigen.rs and had no clue what was going on haha....

I expected to see this happen: Rust bindings for contract generated

Instead, this happened: Macro error

**Comment by gakonst** [comment]
Unfortunately we do not yet have support for the `i256` type.. There's [this](https://github.com/gnosis/ethcontract-rs/blob/8174050ba59d33bcc03910d74f0e8609b648e5d1/ethcontract/src/int.rs#L65) implementation available which we could use.

**Comment by 1saf** [comment]
Is this any workaround for now? E.g. will changing the ABI type to uint256 have much of an impact. Or is there some way I can help bring the implementation to life?

**Comment by gakonst** [comment]
I'd be open to copying over the Gnosis implementation with any compatibility changes and attribution

**Comment by 1saf** [comment]
I will certainly be up to it! What would be a good place to start? I'm sorry if I ask a lot of questions, I am pretty new to Rust!

I went through the source code and was determining how abigen! glued the tokenization together. What I mean by this is how it read the abi file, matched on i256 and subsequently how it would determine to match onto the coming I256 type.

I noticed that there is a reference to I256 already inside the codebase - is this just an alias to U256?

**Comment by gakonst** [comment]
Abigen creates a `I256` token right now [here](https://github.com/gakonst/ethers-rs/blob/master/ethers-contract/ethers-contract-abigen/src/contract/types.rs#L16). Types also get auto-imported [here](https://github.com/gakonst/ethers-rs/blob/master/ethers-contract/ethers-contract-abigen/src/contract/common.rs#L19), so you don't really need to do anything. You just need to implement the `I256` type inside [`ethers-core/src/types`](https://github.com/gakonst/ethers-rs/tree/master/ethers-core/src/types)

**Comment by 1saf** [comment]
Okay I'll give copying across the I256 file across and see how I go. Cheers.

**Comment by 1saf** [comment]
#174 
I added a pull request for this! Please be nice!
