### ISSUE TITLE
U256 operations give different results compared to Solidity uint256 operations

### ISSUE THREAD

**Issue by insanediv** [gakonst/ethers-rs#1695]
**Version**
ethers-rs: 0.17.0

**Platform**
Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

**Description**
Hello,
I noticed that operations performed on U256 types have different level of precision compared to Solidity.

I tried this code:

```solidity
// Solidity
// Will return 536871970353
function getOutput() public returns (uint256){
    uint256 a = 99999640;
    uint256 b = 5368739031;
    uint256 c = 10**6;
    return (a * b) / c; 
}
```

```rust
// Rust
// Will return 536872035553
fn get_output() -> U256 {
    let a = U256::from(99999640);    
    let b = U256::from(5368739031);    
    let c = U256::from(10).pow(6);
    a.mul(b).div(c)
}
```

I expected the Rust function to return `536871970353` instead it returned `536872035553`

**Comment by DaniPopes** [comment]
The following compiles and runs correctly, are you sure it's ethers?

```rust
    use std::ops::{Div, Mul};

    let expected = U256::from(536871970353u64);
    let wrong = U256::from(536872035553u64);

    let a = U256::from(99999640);
    let b = U256::from(5368739031u64);
    // let c = U256::exp10(6);
    let c = U256::from(10).pow(6.into());
    // let res = (a * b) / c;
    let res = a.mul(b).div(c);

    assert_ne!(res, wrong);
    assert_eq!(res, expected);
```

**Comment by insanediv** [comment]
Hello Dani,
thank you for your analisys. You are right it was a bug in my source code.
I'm sorry for that. We can close the issue.

By the way: this is a great library!
