### ISSUE TITLE
ethers-solc build script doesn't error on compilation error

### ISSUE THREAD

**Issue by noot** [gakonst/ethers-rs#1727]
**Version**
ethers v0.17.0

**Platform**
ubuntu 22.04

**Description**

I have a project using the build script defined here to compile contracts: https://github.com/gakonst/ethers-rs/blob/cd2c9f6dd11d12ddb8db64b98531c10852befe0f/ethers-solc/README.md

here's the exact script:
```
use ethers_solc::{Project, ProjectPathsConfig};

fn main() {
  println!("cargo:rerun-if-changed=contracts");
  println!("cargo:rerun-if-changed=artifacts");

  // configure the project with all its paths, solc, cache etc.
  let project = Project::builder()
    .paths(ProjectPathsConfig::hardhat(env!("CARGO_MANIFEST_DIR")).unwrap())
    .build()
    .unwrap();
  project.compile().unwrap();

  // Tell Cargo that if a source file changes, to rerun this build script.
  project.rerun_if_sources_changed();
}
```

I expected  `project.compile().unwrap()` to panic if solc is unable to compile the contracts, however it doesn't, it simply doesn't generate the artifacts/ dir. It would be ideal for it to panic with a message that at minimum says "unable to compile contracts" or something along those lines.

**Comment by mattsse** [comment]
Hey :)

This is expected here because the `Error` here is independent of the solc outcome:

https://github.com/gakonst/ethers-rs/blob/5bca54c41d3fd7fed7ca97c2b2b9e22d0decaa68/ethers-solc/src/lib.rs#L248-L249

But looks like we could use something like `ProjectCompileOutput::ensure_success`

**Comment by noot** [comment]
@mattsse thanks for the pointer! I updated the script to check `ProjectCompileOutput::has_compiler_errors()` and panic if true. while it doesn't show the errors, this is definitely an improvement :)

new script:
```
use ethers_solc::{Project, ProjectPathsConfig};

fn main() {
  println!("cargo:rerun-if-changed=contracts");
  println!("cargo:rerun-if-changed=artifacts");

  // configure the project with all its paths, solc, cache etc.
  let project = Project::builder()
    .paths(ProjectPathsConfig::hardhat(env!("CARGO_MANIFEST_DIR")).unwrap())
    .build()
    .unwrap();
  let compiler_output = project.compile().unwrap();
  assert!(!compiler_output.has_compiler_errors());

  // Tell Cargo that if a source file changes, to rerun this build script.
  project.rerun_if_sources_changed();
}
```

**Comment by gakonst** [comment]
Closing as the question is answered above
