### ISSUE TITLE
Support more unit names

### ISSUE THREAD

**Issue by 0xdapper** [gakonst/ethers-rs#1746]
**Is your feature request related to a problem? Please describe.**
Currently only wei, gwei, ether are supported as units. Support more named units so we can use it in `cast --to-units`. Check https://github.com/web3/web3.js/blob/c924148e34600e61c4d1326a9d30fcec83fa9f97/packages/web3-utils/types/index.d.ts#L25-L52 and https://github.com/ethereum/EIPs/issues/33

**Comment by mattsse** [comment]
this would be an easy pick-off,

simply extending this enum

https://github.com/gakonst/ethers-rs/blob/3681099af328610b429fd22eab5e9f68f693c60c/ethers-core/src/utils/units.rs#L4-L13

**Comment by aga7hokakological** [comment]
Would like to take this. 
I just need to add other units right?

**Comment by mattsse** [comment]
nice.

yes, variants and additional conversions
