### ISSUE TITLE
forge bind  fails to generate rust types due to an ethers-rs bug related to how struct names are derived

### ISSUE THREAD

**Issue by totlsota** [gakonst/ethers-rs#1770]
**Version**

I believe [this](https://github.com/foundry-rs/foundry/blob/master/binder/Cargo.toml) is the closest usef ref as it is what (I think) forge is using for 'bind' generating the issue. 

For reference, my current forge version is `forge 0.2.0 (d95f309 2022-10-07T00:11:56.073110133Z)`

**Platform**

`Linux hostname 5.18.10-76051810-generic #202207071639~1659403207~22.04~cb5f582~dev-Ubuntu SMP PREEMPT_DY x86_64 x86_64 x86_64 GNU/Linux`

**Description**

When running `forge bind`the following error is generated:

```
> forge bind
[⠒] Compiling...
No files changed, compilation skipped
The application panicked (crashed).
Message:  "ATestContract.t" is not a valid Ident
Location: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.46/src/fallback.rs:756

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_call_main<unknown>
      at ./csu/../sysdeps/nptl/libc_start_call_main.h:58
   2: __libc_start_main_impl<unknown>
      at ./csu/../csu/libc-start.c:392
```

@mattsse comment from Foundry Support Telegram group:
> This is an ethers-rs bug related to how struct names are derived

I tried this code: ` forge bind`  (and the same with many flag combinations to exclude/ include etc.)

I expected to see this happen: generated .rs files in ./out/

Instead, this happened: the panic mentioned above.

**Comment by mattsse** [comment]
this looks like an error caused by the `.t` which is invalid in the context of rust ident name.

likely happened when we determine the contract name based on the file name or similar.
