### ISSUE TITLE
Error: (code: -32601, message: the method debug_traceTransaction does not exist/is not available, data: None)

### ISSUE THREAD

**Issue by jackbbhua** [gakonst/ethers-rs#1775]
Error: (code: -32601, message: the method debug_traceTransaction does not exist/is not available, data: None)

i am run the debug_traceTransaction demo has the error above.

**Comment by mattsse** [comment]
I would need a bit more context here.

is this a response from anvil or forge?

does your provider support `debug_traceTransaction`?

**Comment by jackbbhua** [comment]
that is my node is build from bsc github.

**Comment by mattsse** [comment]
but this is an error response, right?

so looks like the node is not configured to support traces and doesn't provide the endpoint?

**Comment by jackbbhua** [comment]
yeah.please close it， I will try to fix it.

**Comment by 0xMelkor** [comment]
> yeah.please close it， I will try to fix it.

BSC node is based on geth. Try enabling the `debug` namespace in your node start command
`--http.api=debug,..`
`--ws.api=debug,..` if needed

**Comment by mattsse** [comment]
@gakonst vote close
