### ISSUE TITLE
Is there a way to get the binary value of a U256?

### ISSUE THREAD

**Issue by manasbir** [gakonst/ethers-rs#1783]

**Comment by jmcph4** [comment]
I can think of a few ways off the top of my head.

Firstly, the definition of `U256` is revealing:

```rust
#[repr(C)]
pub struct U256(pub [u64; 4]);
```

So accessing the inner element directly should work?

```rust
fn foo() -> U256;

/* ... */

let n: U256 = foo();
dbg!(&n.0);
```

**Comment by mattsse** [comment]
`.as_ref()` should return &[u8] I believe and you can format u8 in binary form `format!("0{:b} ", byte);`
