### ISSUE TITLE
fastrlp license?

### ISSUE THREAD

**Issue by gd87429** [gakonst/ethers-rs#1785]
Sorry, this is more of a question than anything:

Looks like Cargo.toml uses [fastrlp@0.1.3](https://github.com/gakonst/ethers-rs/blob/master/ethers-core/Cargo.toml#L14) which happens to be [GPL-3.0-only WITH Classpath-exception-2.0](https://crates.io/crates/fastrlp/0.1.3). Wouldn't that cause an issue in this Apache-2.0 / MIT project?

**Comment by gakonst** [comment]
Hmm. FastRLP used to be Apache until 4 months ago https://crates.io/crates/fastrlp/versions until 0.1.2. I don't want to change our license. Could we fork fastrlp from 0.1.2 and call it a day?

**Comment by gd87429** [comment]
IANAL, so not sure about how it works with the already released current v0.17.0. But for future releases maybe worth just linking to 0.1.2 (or an alternative package)? Btw, I only found out about this from using [cargo deny](https://github.com/EmbarkStudios/cargo-deny). Perhaps worth integrating the same here to avoid similar issues in the future?
