### ISSUE TITLE
Support for U160 and I24 data types when decoding an EthEvent

### ISSUE THREAD

**Issue by Tiergarten** [gakonst/ethers-rs#1798]
I'm looking to decode a log event on a UniswapV3 Pool contract:

```
Swap (index_topic_1 address sender, index_topic_2 address recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)
```

via something like:

```
#[derive(Debug, PartialEq, Eq, EthEvent)]
#[ethevent(name = "Swap")]
pub struct UniswapV3SwapEvent {
    #[ethevent(indexed)]
    sender :       Address,
    #[ethevent(indexed)]
    recipient :    Address,
    amount0 :      I256,
    amount1 :      I256,
    sqrtPriceX96 : U160,
    liquidity :    U128,
    tick :         I24,
}
```

I get an `InvalidData` Err when I try to deserialise the event using the above payload but swapping `U160` for `U256` and `I24` for `I128`, so I assume it's because I'm trying to unpack via the incorrect offsets assumed from the type size.

There aren't currently definitions for `U128` or `I24`, can someone please advise me if there is an existing solution for this or advise the best way to implement it?

Interestingly if I inspect the data payload its 160bytes which would suggest that each non-indexed field should be 256 bits wide, so it's possible something else is wrong here.

Example event data payload from this [transaction](https://etherscan.io/tx/0x1a6f84bb80974ed5035b32e28074863c5b4c1506fc850dac1849def90483a32f#eventlog)

```
0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffe97a787700000000000000000000000000000000000000000000000004064976a8dd00000000000000000000000000000000000000006c0e3a3c1cb7beb3e3439d763e9b000000000000000000000000000000000000000000000000ed474377700282070000000000000000000000000000000000000000000000000000000000031f16
```

Thanks,
Matt

**Comment by roynalnaruto** [comment]
Where are you getting the types `U160` and `I24` from? AFAIK, neither `ethabi` nor `ethers-core` have these types defined.

In general the approach would be:
- Define the type in `ethers-core::types`
- Implement the `Tokenizable` trait for that type

You can refer the implementation for [`I256`](https://github.com/gakonst/ethers-rs/blob/master/ethers-core/src/types/i256.rs) and [`Uint8`](https://github.com/gakonst/ethers-rs/blob/master/ethers-core/src/types/uint8.rs).

Further, @mattsse should be able to give more feedback/guidance :)

**Comment by mattsse** [comment]
using U256 and I256 should work here

**Comment by Tiergarten** [comment]
I'm still getting `InvalidData` trying to deserialise with your suggested changes (struct below). I assume the `InvalidData` is coming from one of the calls into `event.rs` - I'll be looking into these today. 

```
#[derive(Debug, PartialEq, Eq, EthEvent)]
#[ethevent(name = "Swap")]
pub struct UniswapV3SwapEvent {
    #[ethevent(indexed)]
    sender :       Address,
    #[ethevent(indexed)]
    recipient :    Address,
    amount0 :      I256,
    amount1 :      I256,
    sqrtPriceX96 : U256,
    liquidity :    U256,
    tick :         I256,
}
```

**Comment by Tiergarten** [comment]
I've had to disable the following check from `event.rs` in the method `derive_decode_from_log_impl()` in order to get this to work:

```
            quote! {
                let event_signature = topics.get(0).ok_or(#core_crate::abi::Error::InvalidData)?;
                if event_signature != &Self::signature() {
                    //return Err(#core_crate::abi::Error::InvalidData);
                }
            },
```

I assume this is because the `topic0` hash doesn't match that of the struct (as it's using different types).

Based on my use case does this strict check make sense? Should it be optional?

Please let me know your thoughts / suggestions, I'm happy to raise a PR

**Comment by mattsse** [comment]
can you provide them abi_signature in the proc-macro manually and try again?

**Comment by Tiergarten** [comment]
yes, passing in the EVM event signature via `abi_signature` into the `EthEvent` macro fixed the issue.

Thanks for your help.
