### ISSUE TITLE
Dependency `jsonrpc` is no longer maintained

### ISSUE THREAD

**Issue by hexcowboy** [gakonst/ethers-rs#1802]
Dependency [`jsonrpc`](https://github.com/paritytech/jsonrpc) is no longer being maintained or developed in favor of [`jsonrpsee`](https://github.com/paritytech/jsonrpsee). There are a few differences in `jsonrpsee` including dropped support of IPC protocol and probably more.

**Comment by mattsse** [comment]
where is this currently used?

**Comment by hexcowboy** [comment]
sorry wrong repo 😁
