### ISSUE TITLE
`utils::parse_units` only supports numbers up to 2^96

### ISSUE THREAD

**Issue by halo3mic** [gakonst/ethers-rs#1822]
### Version
1.0.0

### Description

The function `ethers::utils::parse_units` supports only parsing of numbers that are less than  2^96 as it is bounded by requirements of `rust_dec::Decimal`.

#### I tried this code:

```rust
use ethers::utils::parse_units;

let e15 = parse_units("1", 15).unwrap();
let e30 = e15 * e15;
assert_eq!(parse_units("1", 30).unwrap(), e30); // fails
```

#### I expected to see this happen: 
Does not revert

#### Instead, this happened: 
Reverts with `DecimalError(ExceedsMaximumPossibleValue)`

**Comment by alexlee85** [comment]
why can't we use bigdecimal crate? 
it's an Arbitrary-precision decimal numbers implemented.
https://github.com/akubera/bigdecimal-rs

**Comment by halo3mic** [comment]
> why can't we use bigdecimal crate? it's an Arbitrary-precision decimal numbers implemented. https://github.com/akubera/bigdecimal-rs

We can, and it is a possible solution. However, it raises the question if it is worth adding an extra library just for conversion while the same functionality can be achieved without the library.

**Comment by alexlee85** [comment]
but seems rust_decimal crate only used by this place in this project ?
we just need use bigdecimal to replace rust_decimal, not an adding action.

**Comment by alexlee85** [comment]
sorry, I see your PR and understand you removed rust_decimal crate also, great job @halo3mic
