### ISSUE TITLE
wasm compilation not working

### ISSUE THREAD

**Issue by ncitron** [gakonst/ethers-rs#1824]
**Version**
1.0.0

**Description**
WASM compilation currently only works if you compile the example in `examples/ethers-wasm` while its still inside the main ethers-rs repo. If you copy the entire contents of the folder somewhere else, compilation will fail with dozens of errors relating to the meo crate (I think it is a dependency of tokio). It seems that any crate the imports ethers-rs fails this way when compiling to wasm in my testing.

Here is what the errors look like: https://pastebin.com/BwcEi9Zk

**Comment by mattsse** [comment]
for some reason tokio is pulled in if you directly depend on ethers.

however I've checked all default features and tokio usage in all subcrates which should be ignored for the wasm target, however iirc there are some issues with mutually exclusive `cfg(condition)` and `cfg(not(condition))` cfgs, which could be relevant here.

**Comment by slumber** [comment]
This is still reproducible if you have `ethers-wasm` as a workspace member. I.e. create folder with the following `Cargo.toml`:
```
[workspace]
members = ["ethers-wasm"]
```

And then try to
```sh
cargo build -p ethers-wasm --target wasm32-unknown-unknown
```

This will try to compile ~70 additional targets and in the end produces the same huge list of errors related to `mio`.

Probably caused by https://nickb.dev/blog/cargo-workspace-and-the-feature-unification-pitfall/

**Comment by QYuQianchen** [comment]
Running into the similar issue here. Our project has one crate for smart contracts where it contains foundry-generated contract bindings, and another crate which uses those bindings and compiles to wasm with wasm-bindgen. The same sets of errors related to mio are reported when running cargo build.

**Comment by slumber** [comment]
> Running into the similar issue here. Our project has one crate for smart contracts where it contains foundry-generated contract bindings, and another crate which uses those bindings and compiles to wasm with wasm-bindgen. The same sets of errors related to mio are reported when running cargo build.

As a workaround you can move wasm crate into a subworkspace via adding
```toml
[workspace]
# nothing here
```
to the bottom of its `Cargo.toml`.
