### ISSUE TITLE
Support for beacon chain API

### ISSUE THREAD

**Issue by jannikluhn** [gakonst/ethers-rs#1835]
Would be nice to have support for the [beacon chain / consensus API](https://ethereum.github.io/beacon-APIs/). For the most part, it's a simple REST API. [For real-time events](https://ethereum.github.io/beacon-APIs/#/Events/eventstream), it uses Server-Sent Events.

**Comment by gakonst** [comment]
@ralexstokes dont you have something that implements this somewhere?

**Comment by ralexstokes** [comment]
still under construction but we support most of the API here: https://github.com/ralexstokes/beacon-api-client

**Comment by gakonst** [comment]
Yep exactly. Closing.
