### ISSUE TITLE
Expose U512 `ethers::types`

### ISSUE THREAD

**Issue by halo3mic** [gakonst/ethers-rs#1836]
If I am not mistaken U512 can only be imported from  `ethers::abi::ethabi::ethereum_types` although most other types are usually imported from `ethers::types`. Is there a specific reason for that? 
I personally think exposing U512 in types would make imports cleaner.

My suggestion is to import it here among other types:
https://github.com/gakonst/ethers-rs/blob/14e038860b17807c148cad08192e0722c86753fb/ethers-core/src/types/mod.rs#L9

**Comment by mattsse** [comment]
sgtm
