### ISSUE TITLE
bug: silent bump of MSRV in d47e34dc5b4edf0014ef5c68db75ca3fc19ab333

### ISSUE THREAD

**Issue by OliverNChalk** [gakonst/ethers-rs#1867]
The commit d47e34dc5b4edf0014ef5c68db75ca3fc19ab333 uses `let else` (specifically here https://github.com/gakonst/ethers-rs/commit/d47e34dc5b4edf0014ef5c68db75ca3fc19ab333#diff-ad8c0cbaf83e8d6e3eeb190c36796b85d9e135bcbebf9ee9686db458fbe6b54aR580) which is Rust 1.65, yet the `Cargo.toml` still states Rust 1.62. Probably worth factoring this usage out or updating the Cargo.toml if this usage is really valuable. I'm running 1.64 and this is the only compile issue at the moment.

@Will-Smith11 would you support factoring out the `let else` usage to avoid a version bump?

**Comment by mattsse** [comment]
+1 on downgrading this by rewriting it

**Comment by Will-Smith11** [comment]
> +1 on downgrading this by rewriting it

whats the benefit of not using the most recent stable version of rust? kinda seems backwards to me

**Comment by OliverNChalk** [comment]
Let's `ethers` be used by older versions of rust, resulting in less forced migrations across the ecosystem. For instance we deploy our `ethers` code on top of a precompiled base image that runs rust 1.64, it would be annoying to have to produce new base images every time a new version of rust is released

**Comment by mattsse** [comment]
@Will-Smith11 you wanna refactor this real quick with a `let ethers = ....ok_or_else(|| eyre::eyre!(...))?` ?

**Comment by Will-Smith11** [comment]
> @Will-Smith11 you wanna refactor this real quick with a `let ethers = ....ok_or_else(|| eyre::eyre!(...))?` ?

yeah i can

**Comment by Will-Smith11** [comment]
@mattsse  also noticed that CARGO_MANIFEST_DIR grabs the crate manifest rather than the head manifest so im gonna also add a fix in for that aswell

**Comment by mattsse** [comment]
sg, can just submit two separate PRs

**Comment by gakonst** [comment]
fixed in #1868
