### ISSUE TITLE
code: -32000, message: invalid sender, data: None

### ISSUE THREAD

**Issue by songtianyi** [gakonst/ethers-rs#1873]
Error happended when do contract call send. The code works very well with eth mainnet, polygon mainnet, and moobeem testnet, but failed with BSC mainnet. What's going wrong?

**Comment by gakonst** [comment]
Need to set the signer's chain id. Alternatively use this API https://github.com/gakonst/ethers-rs/blob/f3eee4cf3fe4b7837148b768c5ee925e612e47b8/ethers-middleware/src/signer.rs#L450
