### ISSUE TITLE
Error while calling txpool_inspect 

### ISSUE THREAD

**Issue by estarriolvetch** [gakonst/ethers-rs#1899]
**Version**
List the versions of all `ethers-rs` crates you are using. The easiest way to get
this information is using `cargo-tree`.
```
ethers = { version = "1.0", features = ["rustls", "abigen"]  }
```
**Platform**
The output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)
```
Linux <my_computer> #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
**Description**
Enter your issue details here.
One way to structure the description:

I got error with `txpool_inspect` method. The RPC endpoint I am using is Quicknode.

This is code I was running:
```rust
let content = client.txpool_inspect().await?;
```
and I got the following error message.

```
Error: MiddlewareError(JsonRpcClientError(SerdeJson { err: Error("Invalid character 'n' at position 0", line: 1, column: 256), text: "{\"pending\":{\"0x00000000009A41862f3b2b0C688b7C0d1940511e\":{\"2964\":\"0x9C97e88452F9159BC7b5df9bcd546042940e4655: 0 wei + 30826 gas × 7000000000 wei\"},\"0x00000000863B56a3C1f0F1be8BC4F8b7BD78F57a\":{\"40\":\"contract creation: 0 wei + 612412 gas × 6000000000 wei\"},\"0x000000920f17A49d80550F044C9Bba7923A9fa36\":{\"3\":\"0x5403871b3ebA8B968381476bca2F10C34a5701A4: 50944227810000 wei + 21000 gas × 5358354608 wei\"},\"0x0000009a1363A910E457a2917c915dD4BA1297CB\":{\"34\":\"0x0000000000b3F879cb30FE243b4Dfee438691c04: 0 wei + 68329 gas × 1744367930 wei\"},\"0x000007cDf16e8173C035eC44E4D8a407d214F0f3\":{\"3\":\"0x5BA50c30A18848e33bBF5B71f26DdeD6Baf9F386: 2034918954089932 wei + 21000 gas × 5000000000 wei\"},\"0x00000e2B6fe65400B3a96c5b13E833B99622875d\":{\"5\":\"0xF74B1 ...
```

The error message sounds like there is a parsing error.

**Comment by mattsse** [comment]
likely related to this section:

> "40":"contract creation: 0 wei + 612412 gas × 6000000000 wei" 

but haven't looked at this in detail yet. probably something off with the type that should represent that value

**Comment by 0xMelkor** [comment]
Can you provide repro steps?

I run this with success:

```rust
#[tokio::main]
async fn main() -> Result<()> {
    let provider = Provider::<Http>::try_from(
        // Test URL from quicknode docs
        "https://burned-autumn-sanctuary.discover.quiknode.pro/d6c97f84cf60e774865811666e602f6dadd23e25/",
    )?;

    let content = provider.txpool_inspect().await?;
    println!("{content:?}");
    Ok(())
}
```

What happens if you set the endpoint as in the example above?
What happens if you run this in a terminal?

```bash
curl YOUR-ENDPOINT-URL \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"txpool_inspect","params":[],"id":1,"jsonrpc":"2.0"}' 
```

**Comment by estarriolvetch** [comment]
Hi @0xMelkor 

1. I ran it with your example, and it is still not working. The node in the example is not working, so I just use the one I have.

2 Please see the output here:
https://gist.github.com/estarriolvetch/8361c813285e537cd373045af248ca25

**Comment by 0xMelkor** [comment]
Hi @estarriolvetch 

looks like @mouseless-eth opened a PR to fix this [1905](https://github.com/gakonst/ethers-rs/pull/1905).
Try to link his branch in your `Cargo.toml`:

`ethers = { git= "https://github.com/mouseless-eth/ethers-rs.git", branch = "fix/txpool_inspect"}`

Let us know if it solves your issue.
