### ISSUE TITLE
Cannot use ethers-rs as dependency (E0034)

### ISSUE THREAD

**Issue by xJonathanLEI** [gakonst/ethers-rs#195]
## Version

`ethers-rs`:

```
ethers-test v0.1.0 (/home/dev/repos/rust/ethers-test)
└── ethers v0.2.0 (https://github.com/gakonst/ethers-rs#457c6465)
    ├── ethers-contract v0.2.0 (https://github.com/gakonst/ethers-rs#457c6465)
    │   ├── ethers-contract-abigen v0.2.0 (https://github.com/gakonst/ethers-rs#457c6465)
    │   │   ├── ethers-core v0.2.0 (https://github.com/gakonst/ethers-rs#457c6465)
    │   ├── ethers-contract-derive v0.2.0 (proc-macro) (https://github.com/gakonst/ethers-rs#457c6465)
    │   │   ├── ethers-contract-abigen v0.2.0 (https://github.com/gakonst/ethers-rs#457c6465) (*)
    │   │   ├── ethers-core v0.2.0 (https://github.com/gakonst/ethers-rs#457c6465) (*)
    │   ├── ethers-core v0.2.0 (https://github.com/gakonst/ethers-rs#457c6465) (*)
    │   ├── ethers-providers v0.2.0 (https://github.com/gakonst/ethers-rs#457c6465)
    │   │   ├── ethers-core v0.2.0 (https://github.com/gakonst/ethers-rs#457c6465) (*)
    ├── ethers-core v0.2.0 (https://github.com/gakonst/ethers-rs#457c6465) (*)
    ├── ethers-middleware v0.2.0 (https://github.com/gakonst/ethers-rs#457c6465)
    │   ├── ethers-contract v0.2.0 (https://github.com/gakonst/ethers-rs#457c6465) (*)
    │   ├── ethers-core v0.2.0 (https://github.com/gakonst/ethers-rs#457c6465) (*)
    │   ├── ethers-providers v0.2.0 (https://github.com/gakonst/ethers-rs#457c6465) (*)
    │   ├── ethers-signers v0.2.0 (https://github.com/gakonst/ethers-rs#457c6465)
    │   │   ├── ethers-core v0.2.0 (https://github.com/gakonst/ethers-rs#457c6465) (*)
    ├── ethers-providers v0.2.0 (https://github.com/gakonst/ethers-rs#457c6465) (*)
    └── ethers-signers v0.2.0 (https://github.com/gakonst/ethers-rs#457c6465) (*)
```

`rustc`:

```
rustc 1.50.0 (cb75ad5db 2021-02-10)
```

## Platform

```
Linux dev 5.8.0-43-generic #49~20.04.1-Ubuntu SMP Fri Feb 5 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

## Description

Adding `ethers-rs` as dependency to a freshly created Rust project results in an error.

### Steps to reproduce

- `cargo init` in an empty directory
- add `ethers = { git = "https://github.com/gakonst/ethers-rs" }` to the `dependencies` section as instructed
- `cargo build`

### Expected result

The project should compile successfully.

### Actual result

Compilation fails with errors:

```
error: aborting due to 43 previous errors

Some errors have detailed explanations: E0034, E0308.
For more information about an error, try `rustc --explain E0034`.
error: could not compile `bitvec`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

### Note

Instead of installing from GitHub, I've also tried using the published crate by adding `ethers = "0.2.0"` instead, but resulted in the same errors.

I can compile the `ethers-rs` repository without issues. **_However_**, the same errors show up once I remove the `Cargo.lock` file. This looks like a dependency issue.

**Comment by prestwich** [comment]
As a temporary measure you can try adding the following to your Cargo.toml

`funty = "=1.1.0"`

**Comment by gakonst** [comment]
This should be fixed in master: https://github.com/gakonst/ethers-rs/blob/master/Cargo.lock#L825-L829, added the [pin to ethers-core](https://github.com/gakonst/ethers-rs/blob/a43299c838db31d050f702087d1eeaf46121ee6a/ethers-core/Cargo.toml#L35-L37), does it work for you?

**Comment by xJonathanLEI** [comment]
Thanks for the quick reply!

@prestwich Unfortunately the workaround doesn't seem to work.

@gakonst The library's lock file does fix the build for `ethers-rs` itself, but it didn't help with the case when it's used as a dependency.

According to the [Cargo book](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries), the lock file of a library is ignored when dependent upon, and thus should be ignored from version control.

As for the pin, it's indeed working now. Thanks for the fix. I pulled the repo right before that commit so I missed it :)

**Comment by xJonathanLEI** [comment]
Closing the issue since it's been fixed in commit [a43299c838db31d050f702087d1eeaf46121ee6a](https://github.com/gakonst/ethers-rs/commit/a43299c838db31d050f702087d1eeaf46121ee6a)

**Comment by gakonst** [comment]
Thanks! This was tracked here https://github.com/myrrlyn/funty/issues/3

**Comment by faea726** [comment]
My Cargo.toml:
```
[dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs" }
```

Result after run cargo update
```
$cargo update
Updating git repository `https://github.com/gakonst/ethers-rs`
error: no matching package named `ethers` found
location searched: https://github.com/gakonst/ethers-rs
```

**Comment by gakonst** [comment]
Try "rustup update", you might be on old rust version

**Comment by faea726** [comment]
> Try "rustup update", you might be on old rust version

Worked perfectly!
Thank you so much!
