### ISSUE TITLE
ContractMetadata Serialization/Deserialization failing on Multi-entry source files

### ISSUE THREAD

**Issue by plotchy** [gakonst/ethers-rs#1960]
**Version**
v1.0.2

**Platform**
linux x86_64

**Description**
Im using the ethers::etherscan lib to download etherscan verified source code, and am cacheing them to a location on disk to preserve to prevent future network requests. Ideally, Id prefer to preserve the response as the `ContractMetadata` struct using the Serialization and `serde_json::to_string_pretty`. The written file looks fantastic, but Im having trouble Deserializing it immediately after.

The below example uses the address from the `contract.rs` tests where the object matches the `SourceCodeMetadata::Metadata { .. }` enum

Ethers Test Code:
ethers-etherscan/src/contract.rs#L523-L539
```rust 
let meta = client
    .contract_source_code("0x8d04a8c79cEB0889Bdd12acdF3Fa9D207eD3Ff63".parse().unwrap())
    .await
    .unwrap();

assert_eq!(meta.items.len(), 1);
assert!(matches!(meta.items[0].source_code, SourceCodeMetadata::Metadata { .. }));
let source_tree = meta.source_tree();
assert_eq!(source_tree.entries.len(), 15);
```

Code example Im running into issues with:
```rust
let client = Client::new(*ethers_chain, api_key).unwrap();

//https://api.etherscan.io/api?module=contract&action=getsourcecode&address=0x8d04a8c79cEB0889Bdd12acdF3Fa9D207eD3Ff63
let request_result = client
    .contract_source_code(address) // 0x8d04a8c79cEB0889Bdd12acdF3Fa9D207eD3Ff63
    .await.unwrap();

std::fs::write(
    format!("{}/{}-{:?}.json", cache_path, network, address),
    serde_json::to_string_pretty(&response).unwrap(),
).unwrap();
let file_contents = std::fs::read_to_string(&format!("{}/{}-{:?}.json", cache_path, network, address)).unwrap();
trace!("test - deserializing cache file into contract_metadata");
let contract_metadata: ContractMetadata = serde_json::from_str(&file_contents).unwrap(); // fails here
```

This is the panic output:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: map, expected a string", line: 3, column: 18)'
```

This is the beginning of the Serialized file. 
```json
[
  {
    "SourceCode": {
      "language": "Solidity",
      "sources": {
        "@openzeppelin/contracts/security/ReentrancyGuard.sol": {
          "content": "// SPDX-License-Identifier: MIT\n\npragma solidit ..."
          },
      },
    }
  }
]
```
It should match `ContractMetadata->Metadata->SourceCodeMetadata->Metadata enum` as shown below:
```rust 
#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SourceCodeMetadata {
    /// Contains metadata and path mapped source code.
    Metadata {
        /// Programming language of the sources.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        language: Option<SourceCodeLanguage>,
        /// Source path => source code
        #[serde(default)]
        sources: HashMap<String, SourceCodeEntry>,
        /// Compiler settings, None if the language is not Solidity.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        settings: Option<serde_json::Value>,
    },
    /// Contains only the source code.
    SourceCode(String),
}
```

Any idea what could be going wrong? Happy to experiment more

**Comment by mattsse** [comment]
since this is a decoding issue, could please get the actual json response and compare it against the current model?

Then we can fix.

**Comment by DaniPopes** [comment]
Etherscan's response's `SourceCode` field is always one big String, we parse that as a JSON object if it starts with 2 `{` characters and then deserialize into the actual objects, otherwise it is just the source code for one file;
When you serialize, it will use the default Serde derive impl so it will be serialized as a normal object, not a string;
When deserializing this last step, it will fail expecting a String
