### ISSUE TITLE
missing CI coverage

### ISSUE THREAD

**Issue by DaniPopes** [gakonst/ethers-rs#1978]
P.S.: CI needs quite the revamp, it's currently only covering Windows with no features and Linux with either all or no features;
@mattsse maybe just copy it over from Foundry?

_Originally posted by @DaniPopes in https://github.com/gakonst/ethers-rs/issues/1976#issuecomment-1365596397_

**Comment by gakonst** [comment]
Yeah copying over x-platform CI from Foundry SGTM.
