### ISSUE TITLE
use ethers::core::types::{ParseChainError, H512};

### ISSUE THREAD

**Issue by polyphia** [gakonst/ethers-rs#1993]
**Version**
├── ethers-core v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607)
    │   │   ├── ethers v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607)
    │   │   │   ├── ethers-addressbook v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607)
    │   │   │   │   ├── ethers-core v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   ├── ethers-contract v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607)
    │   │   │   │   ├── ethers-contract-abigen v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607)
    │   │   │   │   │   ├── ethers-core v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   │   ├── ethers-contract-derive v1.0.2 (proc-macro) (https://github.com/gakonst/ethers-rs#228f9607)
    │   │   │   │   │   ├── ethers-contract-abigen v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607)
    │   │   │   │   │   │   ├── ethers-core v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607)
    │   │   │   │   │   ├── ethers-core v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   │   ├── ethers-core v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   │   ├── ethers-providers v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607)
    │   │   │   │   │   ├── ethers-core v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   ├── ethers-core v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   ├── ethers-etherscan v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607)
    │   │   │   │   ├── ethers-core v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   │   ├── ethers-solc v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607)
    │   │   │   │   │   ├── ethers-core v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   ├── ethers-middleware v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607)
    │   │   │   │   ├── ethers-contract v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   │   ├── ethers-core v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   │   ├── ethers-etherscan v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   │   ├── ethers-providers v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   │   ├── ethers-signers v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607)
    │   │   │   │   │   ├── ethers-core v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   ├── ethers-providers v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   ├── ethers-signers v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   └── ethers-solc v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   ├── ethers-core v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   ├── ethers-etherscan v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   ├── ethers-middleware v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   ├── ethers-providers v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   ├── ethers-solc v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   │   ├── ethers-core v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   │   ├── ethers-etherscan v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   │   ├── ethers-solc v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   ├── ethers-addressbook v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   ├── ethers-contract v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   ├── ethers-core v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   ├── ethers-etherscan v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   ├── ethers-providers v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   ├── ethers-solc v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   │   │   │   ├── ethers-core v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    ├── ethers v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)
    │   ├── ethers v1.0.2 (https://github.com/gakonst/ethers-rs#228f9607) (*)

Does not compile with following error : 

error[E0432]: unresolved import `ethers::core::types::ParseChainError`
  --> relay/src/relay.rs:12:27
   |
12 | use ethers::core::types::{ParseChainError, H512};
   |                           ^^^^^^^^^^^^^^^
   |                           |
   |                           no `ParseChainError` in `types`
   |                           help: a similar name exists in the module: `ParseI256Error`

For more information about this error, try `rustc --explain E0432`.

**Comment by mattsse** [comment]
the parse chain error was deprecated

you can use this instead

```
 type Error = <ethers::types::Chain as TryFrom<u64>>::Error;
```

but I actually like `ParseChainError` more, wdyt @DaniPopes should we quickly add it back?

**Comment by DaniPopes** [comment]
You can't because it's part of the num-enum macro, you can re-export it with an alias i guess
