### ISSUE TITLE
Format Abigen code using `prettyplease`

### ISSUE THREAD

**Issue by DaniPopes** [gakonst/ethers-rs#2026]
Use [dtolnay/prettyplease](https://github.com/dtolnay/prettyplease) internally to format code generated by `Abigen`, instead of `rustfmt`:
- Allows for consistent results across different hosts, toolchains and `rustc` versions
- Doesn't rely on an external binary and all the hurdles that come with invoking one
- Virtually no compilation time overhead as it depends only on `syn` and `proc-macro2`
- [20 times the speed](https://github.com/dtolnay/prettyplease/blob/master/README.md#feature-matrix)
- Used by [cargo-expand](https://github.com/dtolnay/cargo-expand/), [prost](https://github.com/tokio-rs/prost), [yew](https://github.com/yewstack/yew) to name a few
- Made by dtolnay :pray:

More info in the [prettyplease README](https://github.com/dtolnay/prettyplease/blob/master/README.md):

> This library is designed using the simplest possible algorithm and data structures that can deliver about 95% of the quality of rustfmt-formatted output. In my experience testing real-world code, approximately 97-98% of output lines come out identical between rustfmt's formatting and this crate's. The rest have slightly different linebreak decisions, but still clearly follow the dominant modern Rust style.

> The tradeoffs made by this crate are a good fit for generated code that you will not spend your career staring at. For example, the output of `bindgen`, or the output of `cargo-expand`. In those cases it's more important that the whole thing be formattable without the formatter giving up, than that it be flawless.

**Comment by mattsse** [comment]
sgtm
