### ISSUE TITLE
Decoding transaction data seems to be wrong

### ISSUE THREAD

**Issue by finlaydotb** [gakonst/ethers-rs#2039]
**Version**
```
cargo tree | grep ethers
├── ethers v1.0.2
│   ├── ethers-addressbook v1.0.2
│   │   ├── ethers-core v1.0.2
│   ├── ethers-contract v1.0.2
│   │   ├── ethers-contract-abigen v1.0.2
│   │   │   ├── ethers-core v1.0.2 (*)
│   │   ├── ethers-contract-derive v1.0.2 (proc-macro)
│   │   │   ├── ethers-contract-abigen v1.0.2
│   │   │   │   ├── ethers-core v1.0.2
│   │   │   ├── ethers-core v1.0.2 (*)
│   │   ├── ethers-core v1.0.2 (*)
│   │   ├── ethers-providers v1.0.2
│   │   │   ├── ethers-core v1.0.2 (*)
│   ├── ethers-core v1.0.2 (*)
│   ├── ethers-etherscan v1.0.2
│   │   ├── ethers-core v1.0.2 (*)
│   ├── ethers-middleware v1.0.2
│   │   ├── ethers-contract v1.0.2 (*)
│   │   ├── ethers-core v1.0.2 (*)
│   │   ├── ethers-etherscan v1.0.2 (*)
│   │   ├── ethers-providers v1.0.2 (*)
│   │   ├── ethers-signers v1.0.2
│   │   │   ├── ethers-core v1.0.2 (*)
│   ├── ethers-providers v1.0.2 (*)
│   └── ethers-signers v1.0.2 (*)
```

**Platform**
22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64

**Description**

I am trying to decode the hex data of a transaction. For testing purposes I am using the transaction that can be found here https://kovan.etherscan.io/tx/0xad76a2d244b66d44415135dedd03a127bbfdf36bf0eee68a7c857f8dff7be7fa

It clearly states that the function is `Function: addToCurrentNumber(uint256 _toAdd)` hence the input type is `uint256` and the original hex value is `0xa934861a0000000000000000000000000000000000000000000000000000000000000005`

The decoded value can also be seen as 5.

Now in my code I have the following

```
use ethers::abi::decode;
use ethers::abi::ParamType;
use ethers::core::utils::hex::decode as hex_decode;
fn main() {
    let vec1 = hex_decode("a934861a0000000000000000000000000000000000000000000000000000000000000005").unwrap();
    let data: &[u8] = vec1.as_slice();
    let result = decode(
        vec![ParamType::Uint(256)].as_slice(),
        data
    ).unwrap();
    println!("{:?}", result);
}
```

But when I run this, the output is `[Uint(76533672992909578901694265460808195815504318440232336607848770502130973802496)]` which is not what I was expecting. I was expecting 5.

Am I doing something wrong? Or this is working as expected and I am missing the API?

**Comment by DaniPopes** [comment]
You're decoding `a934861a000000...` not `00000...005`:
abi::decode doesn't take into account function selectors or anything -- with ParamType::Uint it just takes the next 32 bytes and interprets them as a uint

do this instead:
```rust
let data = hex_decode("...").unwrap();
let result = decode(&[ParamType::Uint(256)], &data[4..]).unwrap();
```

More info at [ethabi](https://github.com/rust-ethereum/ethabi) (we use this crate for abi encoding and decoding), and [slices](https://doc.rust-lang.org/stable/std/primitive.slice.html)

**Comment by mattsse** [comment]
since you're trying to decode a function call, please have a look at the `EthCall` derive macro

**Comment by finlaydotb** [comment]
> You're decoding `a934861a000000...` not `00000...005`:
> `abi::decode` will just parse the original bytes into the given parameters, without taking into account any function selectors

@DaniPopes Thanks for pointing this out. How will one go about performing a decode that involves passing also the function selector. For example how will the whole `a934861a000000...` be decoded? I took a brief look at the docs again and could not see how.

**Comment by finlaydotb** [comment]
Never mind. The first 4 bytes just needs to be removed. And being able to go from the first four bytes is actually impossible if I am not mistaken. As it is a hash of function name and input and not possible with a cryptographic hash to go back from the hash to the inputs.
