### ISSUE TITLE
how to get mining reward at a specific height? 

### ISSUE THREAD

**Issue by Haider-Ali-DS** [gakonst/ethers-rs#2115]
How can i know if block i fetched using `get_block` is `Byzantine`, `Constantinople` or `Frontier`?
my end goal is to get mining reward for that block and replicate this go function.
https://github.com/coinbase/rosetta-ethereum/blob/master/ethereum/client.go#L1265

**Comment by gakonst** [comment]
You need to check the height of the block and compare accordingly.
