### ISSUE TITLE
Pascal case not applied to struct fields in Abigen

### ISSUE THREAD

**Issue by batconjurer** [gakonst/ethers-rs#2129]
**Version**
This error occurred with `ethers-contract` version `1.0.2`.

**Description**
When generating Rust types for a solidity contract, a solidity struct with the name `ERC20Transfer` led to the creation of a Rust struct called `Erc20Transfer`, because Abigen applies Pascal case formatting to struct names. 

However, suppose another solidity struct existed 
```
struct SomeStruct {
    ERC20Transfer someField;
}
``` 

Then the genereated Abigen code will produce a Rust struct like so:
```rust
struct SomeStruct {
     some_field: ERC20Transfer,
}
```
The obvious fix is to apply Pascal casing to field types when expanding struct definitions. change https://github.com/gakonst/ethers-rs/blob/e20bb715699280402c155a0abbfc82656582242e/ethers-contract/ethers-contract-abigen/src/contract/structs.rs#L599
 
to
```rust
 let ty = util::ident(&ty.name().to_pascal_case());
``` 

Running this on my solidity contracts produced the desired result.

**Comment by mattsse** [comment]
too summarize:
* struct types are created like `Erc20Transfer` but when used as fields it is `ERC20Transfer`?

In that case, I believe this is the correct fix.

**Comment by batconjurer** [comment]
That is correct.

**Comment by mattsse** [comment]
ah yes, nice find.

we use pascal case for the rust type here

https://github.com/gakonst/ethers-rs/blob/e20bb715699280402c155a0abbfc82656582242e/ethers-contract/ethers-contract-abigen/src/contract/structs.rs#L303

Would you like to submit the fix?

**Comment by batconjurer** [comment]
Sure, I have already forked the repo and made the change. 

However, as per the contributing document, I am finding that with running `cargo check --all-features` that the versions of the crates `thiserror` and `anyhow` are using unstable features. Should I attempt to fix this as well, or leave it?
