### ISSUE TITLE
Human readable format is not documented in `abigen!`

### ISSUE THREAD

**Issue by oblique** [gakonst/ethers-rs#2134]
**Version**

1.0.2

**Description**

Human readable format is not documented in `abigen!`. It took me an hour to find where I saw about it in the documentation.
Maybe it would be useful to mention [`AbiParser`](https://docs.rs/ethers/1.0.2/ethers/abi/struct.AbiParser.html) in `abigen!` doc.

**Comment by mattsse** [comment]
oh you're right https://docs.rs/ethers/1.0.2/ethers/contract/macro.abigen.html

sorry about that, do you want to add some examples?
