### ISSUE TITLE
`Solc::compile_source` may return `Ok()` even if all compiler outputs are errors

### ISSUE THREAD

**Issue by prestwich** [gakonst/ethers-rs#2150]
**Description**

Discovered while running deployment example

`cargo run -p examples-contracts --example deploy_from_solidity`

kept getting 

```
thread 'main' panicked at 'could not find contract', examples/contracts/examples/deploy_from_solidity.rs:31:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Added a dbg! to inspect the compiler output:

```
    let compiled = Solc::default().compile_source(source).expect("Could not compile contracts");
    dbg!(&compiled);
```

```
[examples/contracts/examples/deploy_from_solidity.rs:30] &compiled = CompilerOutput {
    errors: [
        Error {
            source_location: None,
            secondary_source_locations: [],
            type: "JSONError",
            component: "general",
            severity: Error,
            error_code: None,
            message: "Invalid EVM version requested.",
            formatted_message: Some(
                "Invalid EVM version requested.",
            ),
        },
    ],
    sources: {},
    contracts: {},
}
```

I would expect a compilation run with no succesful compilation to be `Err(...)`, not `Ok(...)`

**Comment by mattsse** [comment]
error handling for the CompilerOutput could use some work yes.
atm it just returns the parse object and fails if something else went wrong

**Comment by amanusk** [comment]
Also getting this error ` { errors: [Error { source_location: None, secondary_source_locations: [], type: "JSONError", component: "general", severity: Error, error_code: None, message: "Invalid EVM version requested.", formatted_message: Some("Invalid EVM version requested.") }], sources: {}, contracts: {} }`

when running examples (e.g. transfer_erc20), can't figure out the reason. Using `solc-select` to manage solc versions, set to `0.8.19`

@prestwich did you find a way around this :) ?

**Comment by prestwich** [comment]
ya, you should check that the errors is empty and the sources is non-empty after calling this function. However, please note that the solc code has moved to https://github.com/foundry-rs/compilers

**Comment by prestwich** [comment]
closing as no longer in repo scope
