### ISSUE TITLE
Writing a smart contract with a locally stored key?

### ISSUE THREAD

**Issue by dnnagy** [gakonst/ethers-rs#2165]
I'm trying to figure out how to write a contract e.g. call a state-changing function with a locally stored private key. 
Suppose the key is loaded into a `LocalWallet`.

**Comment by CRossel87a** [comment]
let pk = "pk-str without 0x";
let chain_id: u64 = 1; 
let wallet = pk.parse::<LocalWallet>()?.with_chain_id(chain_id);
let url = "http://server";
let provider = Provider::<Http>::try_from(url)?;
let conn = SignerMiddleware::new(provider, wallet.clone());
let tx = TransactionRequest::new().to(to).value(1).gas(gas).gas_price(gas_price).nonce(nonce).chain_id(chain_id);
let pending_tx = conn.send_transaction(tx, None).await?;

**Comment by DaniPopes** [comment]
You can also check out the transaction examples: <https://github.com/gakonst/ethers-rs/tree/master/examples/transactions/examples>
