### ISSUE TITLE
I256 SHR can overflow `usize`

### ISSUE THREAD

**Issue by Jon-Becker** [gakonst/ethers-rs#2174]
**Version**
`ethers = "1.0.0"`

but also occurs on all more recent versions.

**Platform**
Darwin macbook 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64

Note that this issue can only be reproduced on certain machines.

**Description**
Essentially, calling 

```rust
ethers_core::types::i256::I256
fn shr(self, rhs: I256) -> Self::Output
```

overflowed usize and throws:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/64037729/220436412-c4475ecf-c1a1-489f-b9ae-055c3ea41939.png">

I tried this code:

`b.value.shr(a.value)`

where b.value and a.value are both valid `I256` objects. The operation that is causing this issue is 

`340282366920938463463374607431768190071 >> 0`

**Comment by dbelv** [comment]
So the following code doesn't panic:
```
let a = I256::from_dec_str("340282366920938463463374607431768190071").unwrap();
let b = I256::zero();
assert_eq!(a >> b, a);
assert_eq!(a.shr(b), a);
 ```  
 
 Even when messing around 0 will be able to fit in all types, however this code does panic with, 
 'Integer overflow when casting to usize', when performing the shr.
 ```    
let a = I256::from_dec_str("340282366920938463463374607431768190071").unwrap();
let b = I256::zero();
assert_eq!(b >> a, b);
assert_eq!(b.shr(a), b);
```
I'm assuming this is the error as above.

**Comment by Jon-Becker** [comment]
Yes my bad. `b` is `0` and `a` is `340282366920938463463374607431768190071` in this case.

**Comment by DaniPopes** [comment]
The actual panic is [here](https://github.com/paritytech/parity-common/blob/2fb72eea96b6de4a085144ce239feb49da0cd39e/uint/src/uint.rs#L1614) in primitive-types, trying to convert the rightside to usize, after being called in `heimdall::VM::_step`, while executing a SAR opcode. `I256` shift right is not an arithmetic shift right, see: <https://docs.rs/ethers/latest/ethers/types/struct.I256.html#diversion-from-standard-numeric-types>

**Comment by dbelv** [comment]
Yeah, noticed that the panic was within primitive-types last night due to U256 implementation.

I was going to approach with implementation with checking if we need to actually perform the method (i.e. the rhs of a shift will always fit in a u8 otherwise we know its 0) and then either return the known answer or perform the op. 

Although looking at the changes linked seems there was a bit on your mind for clean-up :). I'll leave the implementation decision in your capable hands.

**Comment by Jon-Becker** [comment]
Thank you guys, appreciate it!
