### ISSUE TITLE
Don't truncate `ToString` for `H160`

### ISSUE THREAD

**Issue by hexcowboy** [gakonst/ethers-rs#2175]
**Is your feature request related to a problem? Please describe.**
When using the implementation of H160, using the [`to_string`](https://docs.rs/ethers-core/latest/ethers_core/types/struct.H160.html#impl-ToString-for-H160) method, the hex string is truncated like so: `0x3712…99d8`.

**Describe the solution you'd like**
It would make much more sense to me to have it display the full hexstring address like: `0x37121F74d25262011ABBBcc8D13E6923AEb699d8`.

**Describe alternatives you've considered**
https://stackoverflow.com/a/75509511/16245971 this is the alternative I'm using right now, which doesn't feel intuitive.

**Additional Context**
This is just my opinion but I think users should define their own logic for truncating an H160 if they want to, since there isn't a standard AFAIK. The path for converting H160 -> String is not clear to people without knowledge of `UpperHex` and `LowerHex` traits.

**Comment by mattsse** [comment]
this also caused me some grief, but I think the argument for it is that the debug impl already outputs the entire address so display impl can truncate.

but this is implemented via the uint crate in the primitive-types crates. so nothing we can do here.

**Comment by hexcowboy** [comment]
> this is implemented via the uint crate in the primitive-types crates.

good to know, i'll bring the discussion over there. ty

**Comment by jorgeavaldez** [comment]
I ran into the same issue, but for addresses in particular I found [this function](https://docs.rs/ethers/latest/ethers/utils/fn.to_checksum.html) to print as a checksum address!
