### ISSUE TITLE
Make tx_hash on PendingTransaction public

### ISSUE THREAD

**Issue by xJonathanLEI** [gakonst/ethers-rs#221]
**Is your feature request related to a problem? Please describe.**

I'm using `ethers-rs` in a daemon application that acts in a "fire and forget" fashion. It doesn't care about whether the transactions succeed or not, but only about broadcasting them.

I need to log the transaction hash once a transaction is sent. However, the `tx_hash` field on struct `PendingTransaction` is made private, forcing me to await it and get the receipt instead.

**Describe the solution you'd like**

Simply make the `tx_hash` field on `PendingTransaction` public.

**Note**

_Though I've been using `ethers` in TypeScript for quite a while, I'm pretty new to `ethers-rs` and Rust in general. So please forgive me if I'm missing anything. Thanks!_

**Comment by gakonst** [comment]
You can get the `TxHash` inside a `PendingTransaction` by dereferencing it with a `*`, similarly to how it's done [here](https://github.com/gakonst/ethers-rs/blob/5c1f8f532ac7da117edb86b0e1c734188646ff5d/ethers-contract/tests/contract.rs#L55)
