### ISSUE TITLE
Abigen produces bindings with dependency issues

### ISSUE THREAD

**Issue by FrankieIsLost** [gakonst/ethers-rs#2271]
**Version**
439a0c7de0fb8569178d56933b000d8783805c2f

**Platform**
MacOS

**Description**
https://github.com/gakonst/ethers-rs/pull/2222 seems to have affected binding generation. `forge bind` generates bindings which produce the following errors 

```
error[E0432]: unresolved import `futures_util::try_join`
   |
35 | use futures_util::{lock::Mutex, try_join};
   |                                 ^^^^^^^^ no `try_join` in the root

error: cannot determine resolution for the macro `try_join`
    |
789 |             try_join!(self.resolve_field(ens_name, "avatar"), self.resolve_name(ens_name))?;
    |             ^^^^^^^^
    |
    = note: import resolution is stuck, try simplifying macro imports

    Checking ethers-contract-abigen v2.0.0 (https://github.com/gakonst/ethers-rs#439a0c7d)
```

Relatedly, should the generated `Cargo.toml` file pin ethers to a specific version?

**Comment by DaniPopes** [comment]
How can I reproduce this? And where is the error occurring?

**Comment by DaniPopes** [comment]
Oh I see, it breaks on building the repo, even if you cd into it and build it there it's fine, I'm not sure what this is.
Can you manually set `[package] ... resolver = "1"` in `Cargo.toml`?
