### ISSUE TITLE
Implementing State Overrides for Geth traceCall

### ISSUE THREAD

**Issue by jqphu** [gakonst/ethers-rs#2298]
I was looking to open a PR in order to implement State Overrides for Geth traceCall (https://geth.ethereum.org/docs/interacting-with-geth/rpc/ns-debug#debugtracecall, see the example):

https://github.com/gakonst/ethers-rs/blob/16f9fab75cb43e2d9e4c2b74b68afde7577f0e2f/ethers-core/src/types/trace/geth.rs#L190

However, I had one quick question - the override struct already exists for eth_call inside ether-providers `spoof`: https://github.com/gakonst/ethers-rs/blob/16f9fab75cb43e2d9e4c2b74b68afde7577f0e2f/ethers-providers/src/toolbox/call_raw.rs#L235-L502

Now unfortunately, the geth trace structs are inside ethers-core so we cannot access ethers-providers.

Q: Does it make sense to bring this `spoof` module into ethers-core and have ethers-providers depend on it?

**Comment by mattsse** [comment]
these are different calls, I'm not sure if the geth types are the same, but we need them here anyways so let's start there

https://github.com/gakonst/ethers-rs/blob/16f9fab75cb43e2d9e4c2b74b68afde7577f0e2f/ethers-core/src/types/trace/geth.rs#L190

the page does not mention State Overrides so idk.

**Comment by jqphu** [comment]
I ended up looking at the source. It looks like it's the same format. That said, I couldn't see the same struct being used in ethCall. To be honest, I couldn't even find ethCall - my go skills are poor :P.

TraceCall: https://github.com/ethereum/go-ethereum/blob/master/eth/tracers/api.go#L891
The Config Struct: https://github.com/ethereum/go-ethereum/blob/master/eth/tracers/api.go#L188-L192
The definition of State Override: https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L869-L878

> but we need them here anyways so let's start there

Are you suggesting bringing spoof into ethers-core?

**Comment by DaniPopes** [comment]
Fixed in #2406.
