### ISSUE TITLE
Inner attributes and doc comments makes impossible to `include!` generated bindings with MultiAbigen

### ISSUE THREAD

**Issue by mitinarseny** [gakonst/ethers-rs#2299]
With current version (`2.0.1`) it is impossible use [`include!`](https://doc.rust-lang.org/stable/core/macro.include.html) on bindings generated by `MultiAbigen::write_to_module` at  because of inner attributes and inner doc comments [are injected before actual bindings](https://github.com/gakonst/ethers-rs/blob/16f9fab75cb43e2d9e4c2b74b68afde7577f0e2f/ethers-contract/ethers-contract-abigen/src/multi.rs#L813-L828).

[According to Rust docs](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script) the proper location to store artifacts from build scripts is `$OUT_DIR`:
```rust
pub mod my_contracts {
    include!(concat!(env!("OUT_DIR"), "/", path_for_write_to_module, "/mod.rs"));
}
```

And also it would be great if single-file mode on `write_to_module` generates bindings into actual given `path_for_write_to_module.rs`, not inside `path_for_write_to_module/mod.rs`, so the upper expression can be simplified.

Regardless of this, I want to thank all contributors for development of this comprehensive repo!

**Comment by DaniPopes** [comment]
cc @prestwich

it looks like you can't have outer level attributes when including files?

**Comment by prestwich** [comment]
why would you `include!`? the proc macro generates a valid mod.rs, what is the purpose of including it, versus copying the output into the correct directory during the build script, or immediately after build script execution?

> [According to Rust docs](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script) the proper location to store artifacts from build scripts is $OUT_DIR

is the actual issue here that using abigen/forge bind requires not following this recommendation wrt the output of build scripts? I don't see this as an issue really, as the goal of the tools is explicitly to generate a complete multi-file module, not an includable sub-module 

> it looks like you can't have top level inner attributes when including files in general?

this is true

**Comment by mitinarseny** [comment]
> what is the purpose of including it, versus copying the output into the correct directory during the build script

It is impossible to define rust module with unknown location, since [`#[path]`](https://doc.rust-lang.org/reference/items/modules.html#the-path-attribute) attribute accepts only string literal and therefore you can't use `#[path = concat!(env!("OUT_DIR"), "/some_abigen_module")]`. 

But you [have to](https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script) use `$OUT_DIR`:
> Build scripts may save any output files or intermediate artifacts in the directory specified in the [OUT_DIR environment variable](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts). Scripts should not modify any files outside of that directory.

**Comment by prestwich** [comment]
ya, I'm interpreting `should` as RFC2119, and choosing not to follow the recommendation. The usage this was written for is copying the output to a known location
