### ISSUE TITLE
[BUG] Failed to deserialize etherscan response: data did not match any variant of untagged enum ResponseData

### ISSUE THREAD

**Issue by shekohex** [gakonst/ethers-rs#2324]
**Version**
List the versions of all `ethers-rs` crates you are using.

```
ethers v2.0.2
├── ethers-addressbook v2.0.2
├── ethers-contract v2.0.2
├── ethers-core v2.0.2
├── ethers-etherscan v2.0.2
├── ethers-middleware v2.0.2
├── ethers-providers v2.0.2
├── ethers-signers v2.0.2
└── ethers-solc v2.0.2
```

**Platform**
`Linux workstation 5.15.104-2-MANJARO #1 SMP PREEMPT Thu Mar 23 01:40:42 UTC 2023 x86_64 GNU/Linux`

**Description**

As the title says, there is a bug in etherscan data while working with `Polygon` mainnet or the testnet

I tried this code:  https://github.com/shekohex/ethers-etherscan-issue

I expected to see this happen: To have the gas oracle information

Instead, this happened:

Looks like there is a need to handle a new update with the etherscan returned data!

**Logs**

```rs
  ERROR etherscan: Failed to deserialize response: data did not match any variant of untagged enum ResponseData, res: "{\"status\":\"1\",\"message\":\"OK\",\"result\":{\"LastBlock\":\"41171167\",\"SafeGasPrice\":\"119.9\",\"ProposeGasPrice\":\"141.9\",\"FastGasPrice\":\"142.9\",\"suggestBaseFee\":\"89.82627877\",\"gasUsedRatio\":\"0.399191166666667,0.4847166,0.997667533333333,0.538075133333333,0.343416033333333\",\"UsdPrice\":\"1.15\"}}"
    at /home/shady/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ethers-etherscan-2.0.2/src/lib.rs:205

   INFO ethers_etherscan_issue: Gas Oracle Info, gas_oracle: Err(Serde(Error("data did not match any variant of untagged enum ResponseData", line: 0, column: 0)))
    at src/main.rs:39
```

**JSON Response**

```json
{
    "status": "1",
    "message": "OK",
    "result": {
        "LastBlock": "41171167",
        "SafeGasPrice": "119.9",
        "ProposeGasPrice": "141.9",
        "FastGasPrice": "142.9",
        "suggestBaseFee": "89.82627877",
        "gasUsedRatio": "0.399191166666667,0.4847166,0.997667533333333,0.538075133333333,0.343416033333333",
        "UsdPrice": "1.15"
    }
}
```

**Comment by mattsse** [comment]
looks like we need to change the types from u64 to f64

do you want to give this a try?

**Comment by shekohex** [comment]
After narrowing down the issue to just as simple as this [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dd192e2a0ce6d05faafb55da1837ea24) it returns the error: "invalid digit found in string", line: 7, column: 31" and this points out to the `SafeGasPrice` I guess.

Changing these values to be `f64` Like here in the **updated** [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4b59ea8a8053d0b866f29db23a10375a) Solves the issue.

Will open a PR with the quick fix shortly!
