### ISSUE TITLE
Creating a Signature instance from a String

### ISSUE THREAD

**Issue by pepperoni21** [gakonst/ethers-rs#2337]
Hey,

I would like to verify a signature made from ethers.js, but ethers.js gives me a string as the signature so when passed to Rust, I can't verify it since I don't know any way to convert my string to a Signature.

I didn't find anything in the documentation so I'm asking here.

Thanks for your help!

**Comment by mattsse** [comment]
the Signature struct has both

`TryFrom<[u8]>` and `FromStr` impl, if you have a hex string then "<sig>".parse::<Signature>()` should work

**Comment by pepperoni21** [comment]
Yes it works, thanks a lot!
