### ISSUE TITLE
EthEvent::new method for getting typed event data without instantiating a contract

### ISSUE THREAD

**Issue by gakonst** [gakonst/ethers-rs#234]
**Is your feature request related to a problem? Please describe.**

We could add a new method to `EthEvent`, which would allow us to do something like what we do [here](https://github.com/gakonst/ethers-rs/blob/master/ethers-contract/src/contract.rs#L183-L193).

```rust
trait EthEvent {
    fn new<M: Middleware>(filter: &Filter, provider: &M) -> Result<Vec<Self>, SomeError> {
          let filter = filter.clone().event(Self::abi_signature());
          Event {
               filter,
               provider,
               datatype: PhantomData,
               event: <... something that's compatible with the ABI definition>
         }
    }

    // <... other methods>
}

#[derive(Debug, Clone, EthEvent)]
struct MyEvent {
     address foo;
}

let filter = Filter::new().address(MY_ADDRESS).from_block(0).to_block(100);
let provider = Provider::<Http>::try_from("...")?;
let events = MyEvent::new(filter, provider).query().await?;
```

This allows us to conveniently query and subscribe to strongly typed events, without having to instantiate a full contract object (like we show in the [examples](https://github.com/gakonst/ethers-rs/blob/master/ethers/examples/contract_with_abi.rs#L59-L64))

**Comment by mattsse** [comment]
Already working on this.
Main task is implementing a `EthEvent::decode_log(RawLog) -> Result<Self>` method.
To derive this at build time I'll introduce two more attributes to `EthEvent`: 
* `#[ethevent(anonymous)` as to mark the struct as anonymous
* `#[ethevent(indexed)]` to mark a field as indexed event input

The actual decoding then should be analogous to the already existing `parse_log` method used [here](https://github.com/gakonst/ethers-rs/blob/5f292670fc319b03a1ff017ad84cc0c8e95616e1/ethers-contract/src/base.rs#L133-L148)

**Comment by gakonst** [comment]
Great, agree with this approach! Also somewhat related, https://github.com/gakonst/ethers-rs/issues/98
