### ISSUE TITLE
Remove Dependency on Solc

### ISSUE THREAD

**Issue by gakonst** [gakonst/ethers-rs#24]
**Is your feature request related to a problem? Please describe.**

Currently we require that solc is installed on the user's system in order to use `ethers::utils::Solc`.

**Describe the solution you'd like**

It'd be nice if we could use the [bindings](https://github.com/axic/solc-rust/) behind a nicer API, kind of similar to what @spalladino built [here](https://github.com/spalladino/solc-rs/)

**Describe alternatives you've considered**

Maybe we can get away with not bringing solc in the library and just make the errors nicer? Maybe feature gate it?

**Comment by prestwich** [comment]
Can we document that installing `solc` and setting `ETHERSCAN_API_KEY` are required to run the tests?

**Comment by gakonst** [comment]
> Can we document that installing `solc` and setting `ETHERSCAN_API_KEY` are required to run the tests?

[Good point](https://github.com/gakonst/ethers-rs/pull/58/commits/84c86eaa89d2023db0a3fb05d732a6b4ab16de41).

**Comment by reem** [comment]
The readme now mentions needing solc but it could also mention the version needed - had to do a little guess and check to get the tests running, seems that 0.5.x, 0.6.x, and 0.7.x work but 0.4.x and 0.8.x do not. Potentially also worth linking to `solc-select` (https://github.com/crytic/solc-select) until solc can be removed entirely.

**Comment by gakonst** [comment]
Added solc-select here https://github.com/gakonst/ethers-rs/commit/7eec705cecade43367ac5f3d394f59c9955d4577

**Comment by gakonst** [comment]
On further thought, I'd like the client to be able to choose what version of solidity they use, instead of locking them in one. We'd also have to make the library heavier to install if we added it in the binary.
