### ISSUE TITLE
Support multiple addresses in filters

### ISSUE THREAD

**Issue by gakonst** [gakonst/ethers-rs#240]
# Description

Currently, we only support filtering for [0 or 1 address](https://github.com/gakonst/ethers-rs/blob/master/ethers-core/src/types/log.rs#L123-L126). The [ETH Wiki](https://eth.wiki/json-rpc/API#eth_newfilter) specifies:

> address: DATA|Array, 20 Bytes - (optional) Contract address or a list of addresses from which logs should originate.

We should support multiple addresses to allow e.g. getting all the `Transfer` logs for many tokens. While we're at that, we should also update the `LogMeta` struct to include the [`address`](https://github.com/gakonst/ethers-rs/blob/master/ethers-core/src/types/log.rs#L12) which emitted that log.

Here's how Rust-web3 does it: https://github.com/tomusdrw/rust-web3/blob/master/src/types/log.rs#L90, may just be a matter of switching to `ValueOrArray<Address>`

**Comment by sebastinez** [comment]
Hey @gakonst, I'm currently implementing a event listener that should trigger some Graph queries with ethers-rs.
Would gladly take this issue and check how we could implement this feature.

**Comment by gakonst** [comment]
@sebastinez absolutely - go for it!

**Comment by mattsse** [comment]
@sebastinez fyi https://docs.rs/futures/0.3.16/futures/prelude/stream/select_all/fn.select_all.html
maybe you can use this together with the `EventStream` type

**Comment by sebastinez** [comment]
Thanks @gakonst and @mattsse for the recommendation!
If I understand correctly once I successfully subscribed to a filter I should receive just a single `SubscriptionStream` but I'll keep an eye out for the bundling of streams.

**Comment by gakonst** [comment]
The JSON RPC filter allows you to specify multiple addresses, and they'd all be part of the same stream, yes.

**Comment by sebastinez** [comment]
Hey @gakonst sorry for the delay, I created a PR #370 which should implement this feature.
I'm not quite sure what you mean with.
> While we're at that, we should also update the `LogMeta` struct to include the address which emitted that log.

Since it's working great and the logs are showing the address which emitted that log correctly, if you could give me a hint I could add this to the PR.
