### ISSUE TITLE
Add `Chain::supports_push_zero` function

### ISSUE THREAD

**Issue by mattsse** [gakonst/ethers-rs#2430]
similar to 

https://github.com/gakonst/ethers-rs/blob/748fd27096e713a3965c101ee4de4a46689bd66b/ethers-core/src/types/chain.rs#L313

add `supports_push_zero` helper function that should return true if the chain currently supports push0 opcode (with shanghai update)

**Comment by DaniPopes** [comment]
Fixed in #2431
