### ISSUE TITLE
Feature request for easy casting between H256 and U256

### ISSUE THREAD

**Issue by zemse** [gakonst/ethers-rs#2464]
**Is your feature request related to a problem? Please describe.**
`H256::from_uint` exists thankfully, however U256::from_h256 doesn't.

**Describe the solution you'd like**
an API like `uint_val.to_h256()` + `h256_val.to_uint()` (since it can work without imports) otherwise `H256::from_uint` + `U256::from_hash`.

**Describe alternatives you've considered**
for converting H256 to U256: `U256::from_big_endian(proof.key.as_bytes())`

**Additional context**
No

**Comment by DaniPopes** [comment]
You can use the [`BigendianHash`](https://docs.rs/ethers/latest/ethers/abi/ethabi/ethereum_types/trait.BigEndianHash.html) which is part of the same crate that provides the `H*` and `U*` types
