### ISSUE TITLE
Add polling enums for revm middleware

### ISSUE THREAD

**Issue by 0xJepsen** [gakonst/ethers-rs#2531]
We are building revm middleware for arbiter that is modular and integrates with the ethers middleware trait and thus the larger ethereum rust ecosystem. The main difference for us is that the middleware talks to revm in memory and thus can maintain the desired speed. However we wanted to add revm fields to the pending state enum since we do not want them to be futures. Example [here](https://github.com/primitivefinance/ethers-rs/blob/5ef227c7043fc83b914c962c50e9dcf598392b46/ethers-providers/src/toolbox/pending_transaction.rs#L366-L370). Just want to see if this is a change the community would be open to. Thanks!

**Comment by Autoparallel** [comment]
@0xJepsen we can close this issue.
