### ISSUE TITLE
feat: derive `Serialize` and `Deserialize` for `Event`, `{}Filter`, `Call`, and `Errors` in contract bindings

### ISSUE THREAD

**Issue by Autoparallel** [gakonst/ethers-rs#2599]
**Is your feature request related to a problem? Please describe.**
When working with contract bindings, it would be nice to be able to use `serde` to manage these structs/enums. For instance, if I was doing something like this:
```rust
let mut stream = event.stream().await.unwrap();
                while let Some(Ok(event)) = stream.next().await {
                    println!("Event: {:?}", serde_json::to_string(&event));
                }
```
it would be great to be able to do this serialization so I can, for example, output this all to a CSV nicely.

**Describe the solution you'd like**
For instance, we can just add `Serialize` in the output for the bindings such as here:
```rust
fn expand_events_enum(&self) -> TokenStream {
        let variants = self
            .abi
            .events
            .values()
            .flatten()
            .map(|e| {
                event_struct_name(&e.name, self.event_aliases.get(&e.abi_signature()).cloned())
            })
            .collect::<Vec<_>>();

        let enum_name = self.expand_event_enum_name();

        let mut derives = self.expand_extra_derives();
        let params =
            self.abi.events.values().flatten().flat_map(|err| &err.inputs).map(|param| &param.kind);
        util::derive_builtin_traits(params, &mut derives, false, true);

        let ethers_core = ethers_core_crate();
        let ethers_contract = ethers_contract_crate();

        quote! {
            #[doc = "Container type for all of the contract's events"]
            #[derive(Clone, #ethers_contract::EthAbiType, #derives)]
            pub enum #enum_name {
                #( #variants(#variants), )*
            }
            \\ ~ snip
```
we can just replace `#[derive(Clone, #ethers_contract::EthAbiType, #derives)]` with `#[derive(Clone, Serialize, Deserialize, #ethers_contract::EthAbiType, #derives)]`. Note that this is located [here](https://github.com/gakonst/ethers-rs/blob/c702e6cdece63f3c47f3476c626024c11f4b8cec/ethers-contract/ethers-contract-abigen/src/contract/events.rs#L54-L77). 

**Additional context**
Though I just showed the potential solution for `Event`s, this could be applied to `Call`s, `Error`s, and `{}Filter` objects as well.

**Comment by mattsse** [comment]
I think this is reasonable, perhaps this should reuse the attributes supplies to `abigen!`

**Comment by mattsse** [comment]
see

https://github.com/gakonst/ethers-rs/blob/c702e6cdece63f3c47f3476c626024c11f4b8cec/ethers-contract/ethers-contract-abigen/src/contract.rs#L347-L352

and structs for example:

https://github.com/gakonst/ethers-rs/blob/c702e6cdece63f3c47f3476c626024c11f4b8cec/ethers-contract/ethers-contract-abigen/src/contract/structs.rs#L118-L127

**Comment by Autoparallel** [comment]
Let me give this a shot. 

Do you have a suggestion for testing this? Coming from `forge bind`, maybe it is just best to rebuild foundry and point to my ethers branch?

**Comment by mattsse** [comment]
like this

https://github.com/gakonst/ethers-rs/blob/c702e6cdece63f3c47f3476c626024c11f4b8cec/ethers-contract/tests/it/abigen.rs#L123-L133

and assert `Serialize+Deserialize`

**Comment by Autoparallel** [comment]
Okay fair enough!
