### ISSUE TITLE
Support rust logging

### ISSUE THREAD

**Issue by austinabell** [gakonst/ethers-rs#262]
**Is your feature request related to a problem? Please describe.**
Rust logging through the https://docs.rs/log/0.4.14/log/ interface allows the user to have control over how the logs are output, instead of forcing printing to std out. This can be useful if someone wants to ignore logs from any/all modules, log asynchronously, have variable log levels, or even change where the logs are output.

**Describe the solution you'd like**

`println!` usages switched to `log` equivalents.

**Comment by gakonst** [comment]
We [already](https://github.com/gakonst/ethers-rs/issues/32) do this with tracing! Each request made to the node is logged this way: https://github.com/gakonst/ethers-rs/blob/master/ethers-providers/src/provider.rs#L117-L127

**Comment by austinabell** [comment]
> We [already](https://github.com/gakonst/ethers-rs/issues/32) do this with tracing! Each request made to the node is logged this way: https://github.com/gakonst/ethers-rs/blob/master/ethers-providers/src/provider.rs#L117-L127

Ah okay my bad I didn't see, the files I looked in when checking were using println iirc. I'll have another look to see, maybe I'll make a pass through to swap those?

**Comment by gakonst** [comment]
That sounds good to me! Thank you.
