### ISSUE TITLE
Why contract method call returns unknown(!) type?

### ISSUE THREAD

**Issue by logan272** [gakonst/ethers-rs#2625]
**Version**
2.0.10

**Platform**
MACOS

**Description**

I'm trying incorporating ethers-rs into my project, and I've encountered a confusing issue where all the smart contract calls return an unknown type. 

https://github.com/gakonst/ethers-rs/blob/edf3353cb419451a5eb2e89685e3e26e10783670/examples/contracts/examples/abigen.rs#L74

<img width="1027" alt="Screenshot 2023-10-05 at 23 37 01" src="https://github.com/gakonst/ethers-rs/assets/80801525/0fe2c97f-fb46-4371-a280-36ef517c314a">
<img width="1052" alt="Screenshot 2023-10-05 at 23 38 42" src="https://github.com/gakonst/ethers-rs/assets/80801525/8814bc3e-9a89-47ee-a051-e75b742a7daa">

**Comment by mattsse** [comment]
but does it compile?

this rather looks like an issue with rust-analyzer's intellisense

**Comment by logan272** [comment]
> but does it compile?
> 
> this rather looks like an issue with rust-analyzer's intellisense

yeah, it compiles. I got the same results in both NeoVim and VSCode.

**Comment by logan272** [comment]
This issue only exists when i use the `abigen!` macro to generate the inline smart contracts bindings. The issue gone after i switched to`Abigen`.
