### ISSUE TITLE
Support EIP-2930 / EIP-2718 / EIP-1559

### ISSUE THREAD

**Issue by gakonst** [gakonst/ethers-rs#265]
**Is your feature request related to a problem? Please describe.**

Implement the following EIPs:
* [x] [EIP-2718](https://eips.ethereum.org/EIPS/eip-2718) - Typed Transaction Envelopes
* [x] [EIP-2930](https://eips.ethereum.org/EIPS/eip-2930) - Transaction Type 1
* [ ] [EIP-1559](https://eips.ethereum.org/EIPS/eip-1559) - Transaction Type 2

**Describe the solution you'd like**

I think switching to a union/enum type for transactions and implementing a Serde serializer to use the enum's index as the EIP-2718 `type` could be sufficient for 2718. Then, for 2930, we'd just add a new type that implements access lists. It could probably be something like `struct Transaction2930 { tx: Transaction, accessList: AccessList }` and have it serialize to a flattened format.

**Additional context**
Implementation in ethers-js: https://github.com/ethers-io/ethers.js/commit/c47d2eba4dc741eb5cb754c3ef5064b8ea7ac7cc
Hardhat: https://github.com/nomiclabs/hardhat/pull/1379/files
ethereumjs-monorepo: https://github.com/ethereumjs/ethereumjs-monorepo/pulls?q=is%3Apr+is%3Aclosed+2930

**Comment by gakonst** [comment]
More context: https://blog.mycrypto.com/new-transaction-types-on-ethereum/

**Comment by gakonst** [comment]
Preliminary work: https://github.com/gakonst/ethers-rs/tree/feat/typed-transactions

**Comment by xJonathanLEI** [comment]
Nice. Will need this for EIP-1559.

**Comment by gakonst** [comment]
Yes, adding this ASAP this or the next week.

**Comment by hannydevelop** [comment]
Hey @gakonst can you assign me to this, I'll like to work on it

**Comment by guanqun** [comment]
How's the "typed-transactions" branch? Do we have an ETA here? I'm not trying to push here, just thinking that if it's not quite ready before the next hard fork, I'll have to hack some dirty stuff by myself then.

**Comment by gakonst** [comment]
I haven't been able to work on it more yet..Will try to get an update.

**Comment by guanqun** [comment]
Thank you @gakonst  Take your time.

I did a quick look, the most offending part is the middleware layer. I guess the gas price policies in middleware layer don't quite apply to new EIP1559. similar to web3.py's doc here: https://github.com/ethereum/web3.py/blob/master/docs/gas_price.rst

**Comment by gakonst** [comment]
Done in:
#362 
#357 
#355 
#353
