### ISSUE TITLE
ethers-rs is being deprecated

### ISSUE THREAD

**Issue by DaniPopes** [gakonst/ethers-rs#2667]
ethers-rs is in the process of being deprecated in favor of [Alloy](https://github.com/alloy-rs/) and [Foundry](https://github.com/foundry-rs/).

- `ethers::{abi, contract, core, types}` -> [alloy-rs/core](https://github.com/alloy-rs/core)
  - `ethers_core::types::Chain` -> [`alloy-chains`](https://crates.io/crates/alloy-chains) ([`alloy-rs/chains`](https://github.com/alloy-rs/chains))
  - see also [Introducing Alloy](https://www.paradigm.xyz/2023/06/alloy)
- `ethers::{middleware, providers, signers}` -> [alloy-rs/alloy](https://github.com/alloy-rs/alloy)
- `ethers::etherscan` -> [`foundry-block-explorers`](https://crates.io/crates/foundry-block-explorers) ([foundry-rs/block-explorers](https://github.com/foundry-rs/block-explorers))
  - 1-to-1 port using [Alloy types] and [`foundry-compilers`]
- `ethers::solc` -> [`foundry-compilers`] ([foundry-rs/compilers](https://github.com/foundry-rs/compilers))
  - 1-to-1 port using [Alloy types]

See also the new examples at [`alloy-rs/examples`](https://github.com/alloy-rs/examples).

[Alloy types]: https://crates.io/crates/alloy-primitives
[`foundry-compilers`]: https://crates.io/crates/foundry-compilers

**Comment by GopherJ** [comment]
feel alloy is still missing many things so I didn't understand why do we need to deprecate ethers-rs now.

**Comment by sslivkoff** [comment]
whats a rough timeline for this?

**Comment by gakonst** [comment]
This issue is meant to communicate where each new package will live. Still no action needed. It just means we'll be de-prioritizing new feature reqs/redirecting to the new repos. Bugfixes for crits will be provided. Support will be provided as usual in the chat.

**Comment by daweth** [comment]
I think it's a bit premature for deprecation, what's the reason for moving to alloy?

**Comment by leejw51** [comment]
apis will be the same? , how easy to port?

**Comment by rellfy** [comment]
> feel alloy is still missing many things so I didn't understand why do we need to deprecate ethers-rs now.

The deprecation notice is great. The sooner the better, in fact, so that users know what to expect.

**Comment by rellfy** [comment]
> I think it's a bit premature for deprecation, what's the reason for moving to alloy?

It seems like the reasons are outlined here.

https://www.paradigm.xyz/2023/06/alloy

**Comment by gakonst** [comment]
Hi folks -- I communicated some more context here: https://twitter.com/gakonst/status/1730661854572409118. Ethers-rs is still stable and great and I wouldn't worry about it until we recommend people to start switching. And I assume the ones that are using revm etc. are experienced enough that can get over the hurdle of the current alloy transition cost, given the upside from integrating with bleeding edge low-level unreleased libraries!

**Comment by SidestreamColdMelon** [comment]
Hey @gakonst! Thank you for the deprecation notice and additional explanations.

What I still don't understand is the practical implications of the transition. Particularly: we're still hoping to fix https://github.com/gakonst/ethers-rs/issues/2588 as well as [relevant issues](https://github.com/foundry-rs/foundry/issues/6022) with `forge flatten` command (that depends on `ethers-rs`) in order to complete migration from [dapp tools](https://dapp.tools). If we will submit a PR for #2588 in the next month, can we expect you to review and merge it?

**Comment by gakonst** [comment]
Forge has been ported to use https://github.com/foundry-rs/compilers, so please put your fix there, that should work?

Here's more context on the migration https://www.paradigm.xyz/2023/06/alloy.

**Comment by JourneyToSilius** [comment]
if I start a new project, should I use this library, or should I use Alloy ?

**Comment by immi-sipgate** [comment]
Hello 👋🏼 
if I start a new project, should I use this library, or should I use Alloy ?

**Comment by MarcusWentz** [comment]
Updates on the timeline for deprecation?

**Comment by kayabaNerve** [comment]
As a completely independent commenter, I'd share that I personally moved to alloy a while ago. I did note a few bugs, yet nothing irreconcilable, and I'm happy with the progress on the issues I opened.

If you're able to adopt a git dependency, I'd personally recommend moving forward with alloy.

**Comment by gakonst** [comment]
With the release of alloy 0.1 docs.rs/alloy we're finally done! Alloy is feature complete and we encourage everyone to move over.
