### ISSUE TITLE
H256 and some of the other types truncate the string output like 0x13...141 which imo is horrible/frustrating

### ISSUE THREAD

**Issue by ethereumdegen** [gakonst/ethers-rs#2713]
**Is your feature request related to a problem? Please describe.**
H256 and some of the other types truncate the string output like 0x13...141 which imo is horrible.   Its so godforsaken painful to work with these types especially with databasing on the backend.   The only reason why truncating would be nice i guess is frontend but ... no

**Describe the solution you'd like**
I would like to_string() to output the full normal string like 0x123123211   and perhaps add a to_string_shortened() to output what it outputs now 

**Describe alternatives you've considered**
 

**Additional context**

**Comment by prestwich** [comment]
Those types are from a dependency. please file this issue with the Parity team (repo linked below). In the meantime, the workaround is to use debug formatting instead of display

https://github.com/paritytech/parity-common/

**Comment by gakonst** [comment]
Yep @ethereumdegen you can use `format!("{:?}", foo)` instead.

**Comment by ethereumdegen** [comment]
although this is not obvious or pragmatic is it a rly good solution. alright i guess ill do that.  I dont think i will be the last to find this odd however . thanks

**Comment by gakonst** [comment]
Yep it's been odd for a while to us as well. We've fixed it in docs.rs/alloy-primitives, which is going to be the recommended crate once we're done with the transition.

**Comment by DaniPopes** [comment]
See also https://github.com/paritytech/parity-common/issues/656
