### ISSUE TITLE
Question about casting vector of addresses to ethers::core::types::Bytes type in Uniswap V3 Swap Router

### ISSUE THREAD

**Issue by towhidzei** [gakonst/ethers-rs#2758]
I recently generated Rust bindings for Uniswap V3 Swap Router using abigen, and I noticed that the path field in the swap function now expects the ethers::core::types::Bytes type. However, I have a vector of Ethereum addresses that I would like to pass as the path.

How can I cast a vector of Ethereum addresses to the ethers::core::types::Bytes type?

## Example Code:

```rust
// Sample vector of Ethereum addresses
let addresses: Vec<Address> = vec![
    "0x742d35Cc6634C0532925a3b844Bc454e4438f44e",
    "0x742d35Cc6634C0532925a3b844Bc454e4438f44f",
]
.into_iter()
.map(|s| s.parse().unwrap())
.collect();

// How to cast addresses to ethers::core::types::Bytes?
// ...
```

## Additional Context:

I'm using the Uniswap V3 Swap Router in my Rust project, and I would appreciate any guidance on how to properly cast a vector of Ethereum addresses to the required `ethers::core::types::Bytes` type for the `path` field.

here is the method link:
https://etherscan.io/address/0xe592427a0aece92de3edee1f18e0157c05861564#writeProxyContract#F1

**Comment by DaniPopes** [comment]
You need to implement the encoding or look for libraries that have already done this, like [`uniswap-v3-sdk`](https://crates.io/crates/uniswap-v3-sdk).
