### ISSUE TITLE
should abigen support {"abi": xx }

### ISSUE THREAD

**Issue by guanqun** [gakonst/ethers-rs#293]
**Is your feature request related to a problem? Please describe.**

Some tools generate the abi as the format of a JSON, such as this ```{"abi": <the-actual-abi-here>, ...}```, the current abigen macro doesn't support this out of box, I have to extract the actual-abi out of this JSON.

**Describe the solution you'd like**

abigen can automatically detect this case and parse it properly.

**Comment by gakonst** [comment]
The original Gnosis code did that, I am somewhat skeptical of being opinionated on Truffle/Hardhat/... artifacts when somebody should be able to do `cat <..>.json | jq -r .abi`.

**Comment by guanqun** [comment]
Thank you @gakonst for the explanation. Yeah, it's reasonable.
