### ISSUE TITLE
Add a CLI

### ISSUE THREAD

**Issue by gakonst** [gakonst/ethers-rs#3]
Something similar to https://docs.ethers.io/ethers-app/html/dev-cli.html, https://github.com/ethers-io/ethers-cli

My library of preference for CLIs has been gumdrop, examples:
- https://github.com/celo-org/snark-setup/blob/master/powersoftau/src/cli_common/mod.rs#L25-L68
- https://github.com/celo-org/snark-setup/blob/master/bls-snark-setup/src/cli/contribute.rs#L9-L24
- https://github.com/celo-org/celo-threshold-bls-rs/blob/master/crates/dkg-cli/src/opts.rs

**Comment by OdysLam** [comment]
Relevant resource: [Command Line Interface Guidelines](https://clig.dev/)

**Comment by gakonst** [comment]
No longer relevant after [cast](https://github.com/gakonst/foundry/blob/master/cli/src/cast.rs )
