### ISSUE TITLE
Missing `formatBytes32String` and `parseBytes32String` equivalent

### ISSUE THREAD

**Issue by xJonathanLEI** [gakonst/ethers-rs#307]
**Is your feature request related to a problem? Please describe.**
I'm trying to interact with a contract that accepts _bytes32 strings_.

I looked around the code base but couldn't find anything that allows conversion between `&str` and `[u8; 32]`. Please kindly let me know if I missed it. Otherwise, I'd love to submit a PR for this.

**Describe the solution you'd like**
Basically port the `formatBytes32String` and `parseBytes32String` methods [in ethers.js](https://docs.ethers.io/v5/api/utils/strings/#Bytes32String) over.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mattsse** [comment]
There is no need for utility functions, you can handle this in rust like this:

```rust
    use std::convert::TryInto;

    let mut bytes32 = [0u8; 32];
    let s = "not necessarily len 32";
    bytes32[..s.as_bytes().len()].copy_from_slice(s.as_bytes());
    
    // exact 32
    let s32: String = std::iter::repeat("a").take(32).collect();
    assert_eq!(s32.as_bytes().len(), 32);
    bytes32.copy_from_slice(s32.as_bytes());

    let bytes32: [u8; 32] = s32.as_bytes().try_into().unwrap();
    let s = std::str::from_utf8(&bytes32[..]).unwrap(); // see also from_utf8_unchecked
    assert_eq!(s, s32);
```

**Comment by xJonathanLEI** [comment]
Thanks for the quick reply!

To me the point of having a utility function is to hide such implementation details, such that I don't need to think about things like whether the zeros are padded to the left or right every time I need to do bytes32 encoding & decoding. Also not all users of this library are Ethereum experts.

So to me it makes sense for `ethers-rs` to add these methods, especially as an `ethers.js` port.

**Comment by gakonst** [comment]
Thank you for opening the issue!

Agreed that it'd be nice to have a utility method for this, would you want to open a quick PR?

**Comment by xJonathanLEI** [comment]
Sure. Will do. Thanksss

**Comment by xJonathanLEI** [comment]
When implementing the two utility functions, I found that there seems to be a disagreement between `solc` and `ethers.js` on null termination.

The Solidity compilers [states](https://docs.soliditylang.org/en/latest/types.html#string-literals-and-types) that:

_They do not imply trailing zeroes as in C; "foo" represents three bytes, not four._

and I tried the following code and it does compile (32 in length):

```solidity
bytes32 len_32_string = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
```

Meanwhile in `ethers.js`:

```typescript
if (bytes.length > 31) { throw new Error("bytes32 string must be less than 32 bytes"); }
```

What do you guys think? Shall we:

- allow strings of length 32, just like `solc`; or
- follow the logic in `ethers.js` as we're an `ethers.js` port.

Personally I'd say we should take the former.

**Comment by gakonst** [comment]
Let's go with the former, agreed!

**Comment by mattsse** [comment]
did some digging, and ethers.js apparently does this for security reasons https://github.com/ethers-io/ethers.js/issues/66#issuecomment-413456508 
No I'm not sure whether it's worth it to add one line utility functions for that, and if I'm not mistaken, all the encoding/decoding is done by the ethabi Token/Param anyways

**Comment by xJonathanLEI** [comment]
I read the issue you linked but I think the "security issues" he talks about is related to the "unpredictable behavior" when:

- you convert JavaScript strings to bytes32 as they might be interpreted as hex (with the old implementation, which regards "0x11" as a single byte instead of a 4-byte string;
- you forget to handle strings that are too long.

and it doesn't seem to be related to null termination to me. So, despite being in the same post, I think the null termination part is irrelevant to the "security issues".

The first issue I listed above doesn't apply to Rust as `&str` and `&[u8; 32]` are distinctly typed.

**Comment by gakonst** [comment]
@xJonathanLEI if you want to go ahead with implementing this, go for it. I think that Rust's type system should cover us against the unsafe case in JS

**Comment by xJonathanLEI** [comment]
Sure will do :)
