### ISSUE TITLE
No easy way to manually construct and sign transactions into `Transaction`

### ISSUE THREAD

**Issue by xJonathanLEI** [gakonst/ethers-rs#321]
**Is your feature request related to a problem? Please describe.**

Sometimes you want to have total control over the transaction by manually filling in _all_ the fields (i.e. no RPC calls to find out what the nonce should be, for example). However, `ethers-rs` seems to offer no easy way to do this. To manually construct a transaction ready to be broadcast, you'll need to:

1. Construct a `TransactionRequest` instance and fill in all `Option` fields with `Some` (clearly this is _not_ designed to be used this way);
2. Sign the `TransactionRequest` object with a signer, by calling the (unnessarily) async `sign_transaction()` method, to obtain a `Signature`;
3. Calculate the transaction hash by calling `keccak()` on `rlp_signed()` to figure out transaction hash (this is because you need the hash to construct a `Transaction` object!);
4. Construct the `Transaction` object by unwrapping all the `Option` fields on `TransactionRequest`.

This is unnessarily complicated, since we're actually using the flow which assumes some fields are missing.

**Describe the solution you'd like**

There should be:

- An `UnsignedTransaction` struct type designed specially for this, with none of the fields optional;
- a non-async `sign_transaction()` equivalent that directly turns `UnsignedTransaction` into `Transaction`.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by xJonathanLEI** [comment]
> a non-async `sign_transaction()` equivalent that directly turns `UnsignedTransaction` into `Transaction`.

Alternatively, we can have the function return a `Signature`, for consistency's sake, and add a method to construct `Transaction` from `UnsignedTransaction` and `Signature`.

**Comment by xJonathanLEI** [comment]
This will allow for easily signing transactions in a non-async context, where all the transaction fields are known in advance.

**Comment by xJonathanLEI** [comment]
Oh, also such a `UnsignedTransaction` will only accept an actual address as `to`, not ENS names, as that would introduce the need for RPC calls again.

**Comment by xJonathanLEI** [comment]
Just in case someone needs it, this is the code I'm using right now:

```rust
use ethers::{prelude::*, utils::keccak256};

pub struct UnsignedTransaction {
    pub from: Address,
    pub to: Option<Address>,
    pub gas: U256,
    pub gas_price: U256,
    pub value: U256,
    pub data: Bytes,
    pub nonce: U256,
}

pub async fn sign_transaction(
    signer: &LocalWallet,
    unsigned_transaction: UnsignedTransaction,
) -> Transaction {
    let tx_request = TransactionRequest {
        from: Some(unsigned_transaction.from),
        to: unsigned_transaction.to.map(NameOrAddress::Address),
        gas: Some(unsigned_transaction.gas),
        gas_price: Some(unsigned_transaction.gas_price),
        value: Some(unsigned_transaction.value),
        data: Some(unsigned_transaction.data),
        nonce: Some(unsigned_transaction.nonce),
    };
    let tx_signature = match signer.sign_transaction(&tx_request).await {
        Ok(signature) => signature,
        Err(_) => panic!("Infallible"),
    };

    Transaction {
        hash: keccak256(tx_request.rlp_signed(&tx_signature)).into(),
        nonce: unsigned_transaction.nonce,
        block_hash: None,
        block_number: None,
        transaction_index: None,
        from: unsigned_transaction.from,
        to: unsigned_transaction.to,
        value: unsigned_transaction.value,
        gas_price: unsigned_transaction.gas_price,
        gas: unsigned_transaction.gas,
        input: tx_request.data.unwrap(), // This won't panic as tx_unsigned.data holds a Some()
        v: tx_signature.v.into(),
        r: tx_signature.r.as_fixed_bytes().into(),
        s: tx_signature.s.as_fixed_bytes().into(),
    }
}
```

`unwrap()` is used in constructing `Transaction` to avoid (potentially expensive) data copy, and is actually safe.

**Comment by prestwich** [comment]
Hello, I think you are over-complicating things. Please consult the examples to see the intended usage: [link here](https://github.com/gakonst/ethers-rs/blob/master/ethers/examples/transfer_eth.rs#L16-L21)




> * Construct a `TransactionRequest` instance and fill in all `Option` fields with `Some` (clearly this is _not_ designed to be used this way);

you want the builder pattern (see the example)

> * Sign the `TransactionRequest` object with a signer, by calling the (unnessarily) async `sign_transaction()` method, to obtain a `Signature`;

`Signer::sign_transaction` is necessarily async, as most signers used in prod are async. This includes ledgers, HSMs, RPC, and other remote signers. If you would like to sign a transaction synchronously, consider using the underlying [SigningKey](https://docs.rs/k256/0.9.2/k256/ecdsa/struct.SigningKey.html) for your local wallet. 

@gakonst we should consider having `Wallet<SigningKey>` provide a synchronous signing interface

**Comment by xJonathanLEI** [comment]
Thanks for the detailed answer!

I was aware that one can use the chained (fluent) API for building a transaction manually. However, that pattern still assumes that not all fields are filled. There's no way to enforce all necessary fields are provided at compile time.

As for async, sorry I should have looked deeper into the code before submitting the issue lol. I thought the async was _only_ for looking up the missing fields, and this calling it "unnecessary" in my use case.

Maybe my use case is niche enough that it's better served as a custom utility function similar to what I posted above.

**Comment by prestwich** [comment]
to ensure all fields are present, have your code invoke each builder method (at least) once. the compiler will ensure that each method has a valid argument

**Comment by xJonathanLEI** [comment]
Fair enough, but:

- "calling each method at least once" is not enforceable by the compiler (and should not, as that's not the intended usage). Someone forgetting to call a certain method might unknowingly leave it to be fetched from RPC at runtime;

- the resulting object still has `Option`s for all its fields when they're actually knowingly `Some`.

These issues exist because `TransactionRequest` is _not_ intended for offline signing. My proposed `UnsignedTransaction` _is_.

I'm just gonna use my utility function for now. Please close this issue if you guys believe it's unnecessary to support it in the core. (if that's the case we can probably still add an example though)

**Comment by gakonst** [comment]
@xJonathanLEI Closing this optimistically - please re-open if you think it's still an issue.

The recent EIP-1559 changes made it so that `send_raw_transaction` takes the RLP-bytes which you get via [this](https://github.com/gakonst/ethers-rs/blob/master/ethers-middleware/src/signer.rs#L123-L130) call.

As a result, the flow would be:
```rust
let signature = signer.sign_transaction
let bytes tx.rlp_signed(chain_id, signature)
// ...do whatever you want
```
