### ISSUE TITLE
'parse_units' should support amount in decimal as well

### ISSUE THREAD

**Issue by ganeshrvel** [gakonst/ethers-rs#335]
**Is your feature request related to a problem? Please describe.**

The `ethers::core::utils::parse_units` does not support the amount in decimal well. It expects the amount to be a positive whole number.

The below code throws an error.
```rust
   let amount_in_eth = parse_units("15.10", "ethers").unwrap();
```

Error:
```shell
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FromHexError { inner: InvalidHexCharacter { c: '.', index: 2 } }'
```

**Describe the solution you'd like**
ethers-rs should accept decimals in `parse_units`'s `amount` parameter.

**Describe alternatives you've considered**

**Additional context**
In ethers.js they do in face support decimals in the parseUnits. Ref: https://docs.ethers.io/v5/api/utils/display-logic/#utils-parseUnits

**Comment by onbjerg** [comment]
Why was this closed?
