### ISSUE TITLE
More often releases with minors or latest stable

### ISSUE THREAD

**Issue by stephenctw** [gakonst/ethers-rs#371]
Hello, this is a great project and I think developers can benefit from more frequent releases. What's the releasing schedule? Will there be 0.2.3 soon? There's a bug fix my project want to use is committed after May 28.

Thanks!

**Comment by gakonst** [comment]
Hey - can you temporarily use `master`? I will look into publishing ASAP. There has been a docs.rs building issue for [ethers-core](https://docs.rs/crate/ethers-core/0.4.2) which I haven't resolved so far..

**Comment by gakonst** [comment]
I've started publishing new versions, check out 0.4.4 on crates.
