### ISSUE TITLE
Unable to build on Windows 10

### ISSUE THREAD

**Issue by TimvanScherpenzeel** [gakonst/ethers-rs#393]
Hi,

I'm unable to build the project on Windows 10 because `ethers-providers` has IPC enabled by default which is not a thing on Windows.

https://github.com/gakonst/ethers-rs/blob/635236f061504ba99c0bbbae7a0982ee2cdceac1/ethers-providers/Cargo.toml#L51

**Comment by gakonst** [comment]
Hey @TimvanScherpenzeel can you please check if using #394 addresses the issue? I do not have a windows machine to test it on unfortunately.

**Comment by TimvanScherpenzeel** [comment]
Hi @gakonst, my apologies for the late reply - it works well! Thanks
