### ISSUE TITLE
Tracing & in-process rust EVM instead of Ganache

### ISSUE THREAD

**Issue by gakonst** [gakonst/ethers-rs#4]
@pluriholonomic @brockelmore could you dump a few desired features here?

**Comment by prestwich** [comment]
have you looked at the polka evm  based on sputnik?

**Comment by reem** [comment]
From discussions with @pluriholonomic and others:

 - debuggability, could use existing debuggers such as lldb and rr to investigate errors in solidity code
 - performance, cutting out all IO and most serialization overhead should lead to significant performance improvements
 - safety, could use procedural macros to generate fully typed and safe interface to call contracts, could also lead to performance wins with more aggressive design

Extra:

 - forking with block cache, if I fork from the same block and repeat the same actions it should be possible to cache unchanged blocks, leading to possible large increases in performance for testing changes with many steps
 - contract compilation/abi cache, recompiling contracts can take a large % of testing time for large contracts especially with optimization

**Comment by gakonst** [comment]
We already have fully typed interfaces to contracts [here](https://github.com/gakonst/ethers-rs/tree/master/ethers-contract/ethers-contract-abigen), [example](https://github.com/gakonst/ethers-rs/blob/master/ethers/examples/contract.rs#L10-L17), [codegen sample](https://github.com/yieldprotocol/yield-liquidator/blob/master/src/bindings/controller.rs), [codegen example](https://github.com/gakonst/ethers-rs/blob/master/ethers/examples/abigen.rs).

Agree with everything else and would love any help on that end.

**Comment by gakonst** [comment]
@reem the compilation stuff mentioned is now in the [ethers-solc](https://github.com/gakonst/ethers-rs/tree/master/ethers-solc) package, and an in-process EVM with forking is available in [evm-adapters](https://github.com/gakonst/dapptools-rs/tree/master/evm-adapters), along with a full CLI for testing etc. Full tracing is going to come later, but I think that's enough to close the issue in this repo. Feel free to continue the discussion over at [Foundry's issue](https://github.com/gakonst/foundry/issues/24)
