### ISSUE TITLE
Solc Installer & Version Manager

### ISSUE THREAD

**Issue by gakonst** [gakonst/ethers-rs#442]
**Is your feature request related to a problem? Please describe.**

We currently require that the consumer has solc installed. It'd be nice if they didn't need to, and if we downloaded it for them, and managed the version used even.

**Describe the solution you'd like**

A port of this Python impl https://github.com/crytic/solc-select/blob/master/solc_select/solc_select.py in Rust under `ethers-core`'s Solc struct.

**Comment by gakonst** [comment]
@roynalnaruto built https://github.com/roynalnaruto/solc-vm-rs/, we should integrate it to avoid requiring the user to have pre-installed solc

**Comment by mattsse** [comment]
vote to close now that #547 got merged
