### ISSUE TITLE
Auto impl display for Abigen Event Structs

### ISSUE THREAD

**Issue by gakonst** [gakonst/ethers-rs#507]
**Is your feature request related to a problem? Please describe.**

Right now, printing events in a nice human readable way requires [matching on each event variant](https://github.com/gakonst/dapptools-rs/blob/9c703da4f375753052ad46d4cbf4cdc8ab5945f7/evm-adapters/src/sputnik/cheatcodes/cheatcode_handler.rs#L137-L174) and then formatting the output. This is suboptimal because if there's a large amount of events, it means there's a lot of manual work to be done.

Relatedly, I can see the same issue arising on printing function args related to #506, so it might be helpful to tackle these 2 together.

**Describe the solution you'd like**

Define some encoding rules (e.g. all `Bytes` should be `hex::encode`'d before printing them) and implement `Display` for all `event` and `function` structs emitted by `abigen`.

**Comment by gakonst** [comment]
Maybe erring on the side of simplicity / consistency:
1. Numbers => decimal representations
2. Anything bytes related -> 0x encoding
3. Arrays (independently of fixed/variable length) -> `[ <..>, <..> ]` (where <..> is the inner type's Display impl)

**Comment by mattsse** [comment]
I suppose we should limit this to `abigen!` only and not generate Display when using `EthAbiType` and `EthEvent` directly, which could be unexpected and not intuitive.

**Comment by gakonst** [comment]
My thinking was that the`Display` impl could be a comma separated list of val1,...val_n. We could make the `Debug` impl include the name perhaps if we wanted?

I think that doing it for EthAbiType/EthEvent also makes sense, so i'd be supportive of doing that too - unless you think that it's a footgun in any way
