### ISSUE TITLE
Address recovered from EIP712 struct signature differs between Ledger and Wallet implementation

### ISSUE THREAD

**Issue by sebastinez** [gakonst/ethers-rs#516]
Hi folks,

Working on using the ability to sign a struct with the new Eip712 trait and derive macro but it found a divergence between how the Ledger and the Wallet implementation signs the encoded struct hash, and the signee address that a smart contract returns using a `ecrecover` function

```rs
/// The encoded eip712 payload to be signed.
[141, 121, 46, 2, 93, 58, 190, 150, 20, 195, 88, 218, 130, 150, 197, 99, 184, 149, 178, 157, 188, 156, 138, 181, 49, 221, 19, 132, 203, 97, 135, 151]

/// The Signature that gets returned by signing the payload with a LocalWallet
{
  r: 79865770893275451639175808178507952192629851718732781884621688237624443345747,
  s: 42733071147199090845628331540487276759362293016997477521278730816100529639948,
  v: 27,
}

/// The address of a keystore file vs the recovered address from a solidity smart contract
0x589aa5f2e23da3cce0e13289c5d6fab2646c2aad = 0x589aa5f2e23da3cce0e13289c5d6fab2646c2aad

/// The Signature that gets returned by signing the payload with a Ledger HW
{
  r: 28154581424745245939411447948177125479178002747754055933896495342865066545614,
  s: 14878669590408705366957081261318383581626635578079553970907333265222038138021,
  v: 28,
}

///The address of the Ledger HW does not match the recovered address..
0x1CF47b2EE0BF03de1A22De223B2B94Cd9580d942 != 0xac79765881e2de8f54de06dd22a3db96a53b5daf
```

The smart contract function which I'm using to return the signee:
```solidity
    function _recover(
        bytes32 hash,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) public pure returns (address) {
        require(
            uint256(s) <=
                0x7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A0,
            "ECDSA: invalid signature 's' value"
        );
        require(v == 27 || v == 28, "ECDSA: invalid signature 'v' value");

        // If the signature is valid (and not malleable), return the signer address
        address signer = ecrecover(hash, v, r, s);
        require(signer != address(0), "ECDSA: invalid signature");

        return signer;
    }
```
I saw that in the `LedgerEthereum` implementation the `sign_message` function has some prepending.
https://github.com/gakonst/ethers-rs/blob/c3528b78db973b41b4033b9cfdb61734d59515df/ethers-signers/src/ledger/app.rs#L129
It seems it is necessary for the Ledger HW to be able to sign the message. Could it be possible that this diverges the final recovered address?

I'm trying to fix this, but since it works using the LocalWallet implementation it seems to be an issue with the Ledger implementation. 

I add @Ryanmtate to this issue, so he is up to date.

**Comment by Ryanmtate** [comment]
Reading through the ledger `app-ethereum` I found some [documentation](https://github.com/Ryanmtate/app-ethereum/blob/master/doc/ethapp.asc#sign-eth-eip-712) on ledger's `sign eth eip712` method.

Going to see if I can use this information to fix the `sign_typed_data` method.

**Comment by prestwich** [comment]
@Ryanmtate please include a firmware check to prevent attempted signing on outdated devices

> This command has been supported since firmware version 1.5.0

**Comment by Ryanmtate** [comment]
> @Ryanmtate please include a firmware check to prevent attempted signing on outdated devices
> 
> > This command has been supported since firmware version 1.5.0

I noticed a [method](https://github.com/gakonst/ethers-rs/blob/master/ethers-signers/src/ledger/app.rs#L104) to return the ethereum app, but don't immediately know how to check the ledger firmware version.

We could enforce that the ethereum app version must be greater than [v1.6.0](https://github.com/LedgerHQ/app-ethereum/issues/105#issuecomment-765316999), which might suffice for preventing unsupported use in older devices.

Will add this check at the very least.
