### ISSUE TITLE
Clearly separate Unit Tests from Integration Tests

### ISSUE THREAD

**Issue by gakonst** [gakonst/ethers-rs#525]
**Is your feature request related to a problem? Please describe.**

In our tests we frequently call out to 3rd party providers: Infura, Etherscan, Alchemy, various Gas Oracles and so on. These tests are mixed inside the unit test code. Sometimes these tests fail for 3rd party reasons (rate limiting, service down, 2 PRs opened at the same time causing nonce-reuse etc.) and they can cause confusion.

**Describe the solution you'd like**

It'd be nice if we could:
1. Refactor all tests that use the local blockchain (Ganache/Geth locally spun up) w/o any 3rd party deps to be unit tests
2. Refactor all tests that use 3rd party providers to be integration tests (i.e. under a crate's `test/` dir)
3. (Maybe) Create a separate CI pipeline which ONLY runs the integration tests and make the current CI pipeline only run the unit tests

**Comment by Inphi** [comment]
Just wanna note that it isn't yet feasible to use ganache/hardhat in particular as a local blockchain as they're [missing](https://github.com/trufflesuite/ganache/issues/1470) certain EIP-1559 features.

**Comment by makluganteng** [comment]
i wanna take this task

**Comment by gakonst** [comment]
@prestwich thoughts? Or should we hold off on all these?

**Comment by prestwich** [comment]
the tests that I know of, that we need to separate are 

- solc
- geth
- etherscan
- infura
- examples

**Comment by makluganteng** [comment]
Okey i can try first and if i have anything to ask i could ask through TG .

**Comment by mahmudsudo** [comment]
can i take on this task also

**Comment by gakonst** [comment]
Given we're transitioning to Alloy, closing this...Please consider porting over any tests into https://github.com/alloy-rs/core and https://github.com/alloy-rs/alloy (once we're open sourced)
