### ISSUE TITLE
Abigen fails with some nested structs

### ISSUE THREAD

**Issue by sveitser** [gakonst/ethers-rs#538]
**Version**
```
└── ethers v0.5.3 (https://github.com/gakonst/ethers-rs#eede86df)
    ├── ethers-contract v0.5.3 (https://github.com/gakonst/ethers-rs#eede86df)
    │   ├── ethers-contract-abigen v0.5.3 (https://github.com/gakonst/ethers-rs#eede86df)
    │   │   ├── ethers-core v0.5.4 (https://github.com/gakonst/ethers-rs#eede86df)
    │   ├── ethers-contract-derive v0.5.3 (proc-macro) (https://github.com/gakonst/ethers-rs#eede86df)
    │   │   ├── ethers-contract-abigen v0.5.3 (https://github.com/gakonst/ethers-rs#eede86df) (*)
    │   │   ├── ethers-core v0.5.4 (https://github.com/gakonst/ethers-rs#eede86df) (*)
    │   ├── ethers-core v0.5.4 (https://github.com/gakonst/ethers-rs#eede86df) (*)
    │   ├── ethers-providers v0.5.4 (https://github.com/gakonst/ethers-rs#eede86df)
    │   │   ├── ethers-core v0.5.4 (https://github.com/gakonst/ethers-rs#eede86df) (*)
    ├── ethers-core v0.5.4 (https://github.com/gakonst/ethers-rs#eede86df) (*)
    ├── ethers-middleware v0.5.3 (https://github.com/gakonst/ethers-rs#eede86df)
    │   ├── ethers-contract v0.5.3 (https://github.com/gakonst/ethers-rs#eede86df) (*)
    │   ├── ethers-core v0.5.4 (https://github.com/gakonst/ethers-rs#eede86df) (*)
    │   ├── ethers-providers v0.5.4 (https://github.com/gakonst/ethers-rs#eede86df) (*)
    │   ├── ethers-signers v0.5.3 (https://github.com/gakonst/ethers-rs#eede86df)
    │   │   ├── ethers-core v0.5.4 (https://github.com/gakonst/ethers-rs#eede86df) (*)
    ├── ethers-providers v0.5.4 (https://github.com/gakonst/ethers-rs#eede86df) (*)
    └── ethers-signers v0.5.3 (https://github.com/gakonst/ethers-rs#eede86df) (*)
```
**Platform**

`Linux lulus 5.10.75 #1-NixOS SMP Wed Oct 20 09:45:06 UTC 2021 x86_64 GNU/Linux`

**Description**
Some combinations of nested structs and arrays are not handled correctly by the `abigen`.

Example:
```rust
use ethers::prelude::abigen;

abigen!(
    Test,
     r#"[
        struct Outer {Inner inner; uint256[] arr;}
        struct Inner {uint256 inner;}
        function myfun(Outer calldata a)
    ]"#,
);
```

I expected to see this happen: `cargo check` succeeds.

Instead, this happened: 
```
error: Unable to determine ABI: myfun(((uint256),uint256[]))
  --> src/lib.rs:3:1
   |
3  | / abigen!(
4  | |     Test,
5  | |      r#"[
6  | |         struct Outer {Inner inner; uint256[] arr;}
...  |
9  | |     ]"#,
10 | | );
   | |__^
   |
   = note: this error originates in the macro `abigen` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by sveitser** [comment]
I'm unfortunately still affected by this issue. As a first step towards fixing it I was trying to find a place in ethers-rs where the failing example could be added as a (regression) test, but I didn't succeed. If that even makes sense, is there a place where it would make sense to add this?

And in the meantime I'm also wondering if anyone was aware of any workarounds. This seems to affect most of my contracts with nested structs.

**Comment by sveitser** [comment]
I was looking at the code below and wouldn't the example above be parsed as a function in the `parse_function` function?

https://github.com/gakonst/ethers-rs/blob/24f9bd0f4f94eecb173e39e896eeed1040a0948c/ethers-contract/ethers-contract-derive/src/call.rs#L29-L62

**Comment by mattsse** [comment]
thanks for the follow up.
all technical blockers for this have been resolved, however supporting this directly in abigen! requires some refactoring, which I haven't gotten to yet.

workaround currently would be to define the input as tuple `function myfun((...) a)` and the structs standalone with `EthAbiType` and a helper to either encode and decode as Tuple like
`contract.my_fun(outer.encoded().unwrap().decode().unwrap())` or a conversion to tuple directly

**Comment by mattsse** [comment]
> I was looking at the code below and wouldn't the example above be parsed as a function in the `parse_function` function?
> 
> edit: I might get it now that the ABI at that point is already incorrect?
> 
> https://github.com/gakonst/ethers-rs/blob/24f9bd0f4f94eecb173e39e896eeed1040a0948c/ethers-contract/ethers-contract-derive/src/call.rs#L29-L62

the parser is really not ideal and now that we've `ParamType` support, we should be able to bypass that entirely during abigen! expansion, but this is a bit more refactoring effort.

**Comment by sveitser** [comment]
Thanks for the replies. In terms of workarounds for contracts in development, I noticed that sometimes the failures can be avoided by reordering the fields in the structs. The example above compiles if the order of the fields in `Outer` is changed.

```rust
use ethers::prelude::abigen;

abigen!(
    Test,
     r#"[
        struct Outer {uint256[] arr; Inner inner;}
        struct Inner {uint256 inner;}
        function myfun(Outer calldata a)
    ]"#,
);
```

**Comment by sveitser** [comment]
Probably not very useful but in case someone is hitting a similar issue some more information and a reduced real world example (where I can't find a workaround) below. I'm not sure this is hitting the same problem.

The last ethers commit I can expand the abigen macro with is 071a41605ba2a9bffbf618921534ba5e0121f9d8 , the commit where it started breaking is fb4d9a9ef1cc9df340023d61a6885693a6a6fcf5.

Fails with 
```
error: Unable to determine ABI: submitBlock((uint64,((((uint256,uint256,uint256,uint256),uint256[]),uint256[],uint256[]))[],((((uint256,uint256,uint256,uint256),uint256[]),uint256[],uint256[]))[]))
```


```solidity
pragma solidity ^0.8.0;

contract CAPE {

    struct EncKey {
        uint256 x;
        uint256 y;
        uint256 t;
        uint256 z;
    }

    struct AuditMemo {
        EncKey ephemeral;
        uint256[] data;
    }

    struct TransferNote {
        AuditMemo auditMemo;
        uint256[] inputsNullifiers;
        uint256[] outputCommitments;
    }

    struct Transaction {
        TransferNote note;
    }

    struct Block {
        uint64 blockHeight;
        Transaction[] txns;
        Transaction[] burnTxns;
    }

    function submitBlock(
        Block memory newBlock
    ) public {
    }
}
```

**Comment by mattsse** [comment]
thanks for these,
the whole reason this fails is because abigen! utilizes ethabi's tuple parser that has some troubles with nested tuples apparently, 
I'll try to revamp the whole abigen type detection this weekend.

**Comment by mfw78** [comment]
Hello, I've come across this github issue when attempting to use `forge` and `ethers-rs`. After successfully testing the contracts in `forge`, I used `forge bind` to generate bindings for the project. When attempting to use one of the generated bindings, the following error was thrown:

```raw
133 |         pub diamond_cut: Vec<(ethers::core::types::Address, u8, Vec<[u8; 4]>)>,
    |         ^^^ the trait `AbiArrayType` is not implemented for `u8`
    |
    = note: required because of the requirements on the impl of `AbiArrayType` for `(H160, u8, Vec<[u8; 4]>)`
    = note: required because of the requirements on the impl of `AbiType` for `Vec<(H160, u8, Vec<[u8; 4]>)>`
```

The solidity source code for this is available at https://github.com/mudgen/diamond-3-hardhat/blob/main/contracts/interfaces/IDiamondCut.sol.

**Comment by mattsse** [comment]
thanks, it appears there are some `AbiArrayType` impls missing for tuples
I'll check
