### ISSUE TITLE
Return uuid when create a new keystore from LocalWallet

### ISSUE THREAD

**Issue by stephenctw** [gakonst/ethers-rs#557]
Currently the `LocalWallet::new_keystore()` doesn't return the `uuid` that's available from the inner [`eth_keystore::new`](https://docs.rs/ethers-signers/0.5.4/src/ethers_signers/wallet/private_key.rs.html#72) call. Making it impossible to manage the keystore in the filesystem programmatically. Please also return the `uuid` from `eth_keystore::new` so the actual keystore file can be located easily.

**Comment by gakonst** [comment]
@roynalnaruto FYI

**Comment by roynalnaruto** [comment]
@stephenctw Thanks for having created the issue. I've made the necessary changes in the above linked PR 👍

**Comment by gakonst** [comment]
@stephenctw closing, please re-open if the PR doesn't address your problem!
