### ISSUE TITLE
Deserialising a raw signed transaction?

### ISSUE THREAD

**Issue by except** [gakonst/ethers-rs#561]
Is there an example on how to deserialize a raw transaction from a byte array? I looked through the API docs but I didn't seem to find one.

**Comment by mattsse** [comment]
the transaction type is

https://github.com/gakonst/ethers-rs/blob/dcf20022c66921779059bbfc58f5d378d20b84be/ethers-core/src/types/transaction/eip2718.rs#L25-L35

There is currently no rlp decoding support I believe, but it should be possible to add that by reversing the `rlp` encoding functions:

https://github.com/gakonst/ethers-rs/blob/dcf20022c66921779059bbfc58f5d378d20b84be/ethers-core/src/types/transaction/eip2718.rs#L201-L219

**Comment by gakonst** [comment]
Yep should be doable that way. Also note that there's macros for [rlp encoding / decoding from the RLP crate](https://docs.rs/rlp-derive/0.1.0/rlp_derive/) which we use [here[(https://github.com/gakonst/ethers-rs/blob/master/ethers-core/src/types/transaction/eip2930.rs#L5). PRs welcome!
