### ISSUE TITLE
To include tx_hash and input data in TxpoolTransaction

### ISSUE THREAD

**Issue by KennyYanXM** [gakonst/ethers-rs#576]
currently TxpoolTransaction is a synonym of TransactionRequest and it doesn't include "tx_hash" and not deserilize input data.
It's very useful to add these too fields for TxpoolTransaction.

**Comment by gakonst** [comment]
WIP on this here https://github.com/gakonst/ethers-rs/pull/465, if you want to try getting it over the line?
