### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by gakonst** [gakonst/ethers-rs#6]
- e.g. eth/erc20 unified client https://gist.github.com/gakonst/f979eab30a61cdfb696050c6786a52dc

**Comment by paulrberg** [comment]
It would be particularly helpful to have some examples for how to work with the new `PendingTransaction` type added in v0.2.0

I think it should be something like this:

```rust
pub struct MyStruct<'a, M, P> {
    ...
    my_contract: MyContract<M>,
    pending_transactions: HashMap<Address, PendingTransaction<'a, P>>,
    ...
)
```

And then, if you want to send a contract call and work with the [send](https://github.com/gakonst/ethers-rs/blob/0.2.0/ethers-contract/src/call.rs#L129-L134) method, the `impl` block should look something like this:

```rust
impl<'a, M, P> Liquidator<'a, M, P>
where
    M: Middleware<Provider = P> + 'a,
    P: JsonRpcClient + 'a,
{
    // your methods that send a contract call
}
```

I find it difficult to arrive at the configuration above, so presenting in the documentation would go a long way, imo.

Conversely, there is the possibility that the above is not the *intended* behaviour (as per the [implementation](https://github.com/gakonst/ethers-rs/blob/0.2.0/ethers-providers/src/pending_transaction.rs#L167-L173) of the Deref trait). If this is the case, users are not expected to create instances of `PendingTransaction` - only to dereference them and grab the transaction hashes.

**Comment by gakonst** [comment]
Managing pending transactions is a bit tricky, as you say, in the [escalator](https://github.com/gakonst/ethers-rs/blob/master/ethers-middleware/src/gas_escalator/mod.rs#L67) middleware I only use `TxHash` and not `PendingTransaction`.

A good first step towards simplifying that syntax would be to remove `Provider<P>` from `PendingTransaction` and replace it with `M: Middleware`.

**Comment by gakonst** [comment]
This is going to be ongoing, so just closing
