### ISSUE TITLE
subscribe_blocks() is not working

### ISSUE THREAD

**Issue by stephenctw** [gakonst/ethers-rs#684]
**Version**
0.6.2

**Platform**
WSL2 (Linux LAPTOP-163CP44A 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)

**Description**
ethers::provider::subscribe_blocks() not responding, the wss endpoint is valid that subscribe_pending_txs() is working properly.

I tried this code:

```
use ethers::prelude::*;
use ethers_providers::Ws;

use std::time::Duration;

#[tokio::main]
async fn main() -> std::result::Result<(), Box<dyn std::error::Error>> {
    let ws_endpoint = "wss://goerli.infura.io/ws/v3/<PROJECT_ID>";

    let ws = Ws::connect(ws_endpoint).await?;

    println!("endpoint ready?: {}", ws.ready());

    let provider = Provider::new(ws).interval(Duration::from_millis(2000));

    let mut stream = provider.subscribe_blocks().await?.take(5);
    // let mut stream = provider.subscribe_pending_txs().await?.take(5);

    println!("Stream created! Entering loop...");
    while let Some(block) = stream.next().await {
        dbg!(block);
    }

    Ok(())
}
```

**Comment by gakonst** [comment]
Given that we're not hitting this bug in the [test](https://github.com/gakonst/ethers-rs/blob/master/ethers-providers/src/provider.rs#L1350-L1359) I wonder if this has to do with some network delay / bug in our websocket implementation?

**Comment by stephenctw** [comment]
I can confirm `subscribe_blocks()` is working fine with local hardhat node. `subscribe_pending_txs()` works with goerli + infura.

**Comment by gakonst** [comment]
This is quite weird. I tested with Alchemy and it's working, but I am not getting any results from Infura. (Same code as yours, just replaced Infura URL with Alchemy)

**Comment by lerencao** [comment]
> I can confirm `subscribe_blocks()` is working fine with local hardhat node. `subscribe_pending_txs()` works with goerli + infura.

Is your serde_json  `arbitrary_precision` enabled ?
I met the same problem, and found out it related to serde_json.

**Comment by stephenctw** [comment]
> > I can confirm `subscribe_blocks()` is working fine with local hardhat node. `subscribe_pending_txs()` works with goerli + infura.
> 
> Is your serde_json `arbitrary_precision` enabled ? I met the same problem, and found out it related to serde_json.

Can you give an example how it works with the `arbitrary_precision` feature enabled?

**Comment by stephenctw** [comment]
@lerencao do you have a working example with the `arbitrary_precision` feature?
