### ISSUE TITLE
`fill_transaction` does not delegate to inner

### ISSUE THREAD

**Issue by prestwich** [gakonst/ethers-rs#696]
**Description**

the `Middleware::fill_transaction` method doesn't delegate to inner middleware. It's implemented as a default on the Middleware trait, and the default impl never delegates. This means that `fill_transaction` modifications (e.g. the `NonceManager` middleware) do nothing unless that middleware is the outermost middleware in the stack (the first call in the middleware stack).

Would we rather:

1. delegate to inner at the end of the function
   - con: inner middleware can't distinguish between user-set and default-impl-set attributes 

2. delegate to inner at the beginning of the function
   - con: outer middleware can't distinguish (as above)

3. move the default implementation to the provider 
   - con: any middleware-based adjustment of RPC req/resp contents will be ignored (e.g timelagmiddleware)

**Comment by gakonst** [comment]
closed in #697
