### ISSUE TITLE
Consider making ethers-solc RELEASES offline first

### ISSUE THREAD

**Issue by mattsse** [gakonst/ethers-rs#751]
rn the `RELEASES` static does make a http request to retrieve all versions.

alternatively, we can hard code this as a list or even static array

Upside is that we can get rid of the request overhead
downside is manually updating this list with every new release

**Comment by gakonst** [comment]
I am OK with us hardcoding the values, and we can add a test that runs on CI every day which checks if it's out of sync? 

The error is handled right now by the way: https://github.com/gakonst/ethers-rs/blob/debd1dd153bf7f4bfbfecdebb39b7afa426cdd47/ethers-solc/src/compile.rs#L53-L65.

Think there might be some other calls from svm-rs which we do which end up making network requests.

**Comment by gakonst** [comment]
Closed in #759
