### ISSUE TITLE
[ci] check all examples

### ISSUE THREAD

**Issue by mattsse** [gakonst/ethers-rs#760]
cargo check has an `--examples` flag to check all examples, alternatively
however this only checks and does not run

to run all we can use something like 
https://github.com/gakonst/foundry/blob/master/.github/workflows/integration-tests.yml#L13
to cargo run every rust file in the examples folder

**Comment by dbelv** [comment]
@mattsse was this covered by your work in https://github.com/gakonst/ethers-rs/pull/1286?
