### ISSUE TITLE
unknown field chainId when trying to deploy contract with forge

### ISSUE THREAD

**Issue by FredCoen** [gakonst/ethers-rs#877]
when deploying a contract to kovan with forge create getting the following error

(code: -32602, message: Invalid params: unknown field chainId, expected one of type, from, to, gasPrice, maxFeePerGas, gas, value, data, nonce, accessList, maxPriorityFeePerGas., data: None)

Version: forge 0.1.0 (8107afe 2022-01-31T10:48:23.593667+00:00)

**Comment by gakonst** [comment]
This was only detected in Kovan, which makes me think that OpenEthereum nodes cannot deserialize the `chainId` field. Related to #805 cc @Rjected
