### ISSUE TITLE
Make `Chain`'s `to_string` and `from_str` inverse functions 

### ISSUE THREAD

**Issue by meetmangukiya** [gakonst/ethers-rs#897]
**Is your feature request related to a problem? Please describe.**
Currently, `to_string` and `from_str` are not mirroring each other, maybe they should.

**Describe the solution you'd like**
Make `to_string` and `from_str` inverse functions 

```rs
let chain_name = "mainnet";

let chain = Chain::from_str(chain_name)?;
assert_eq!(chain.to_string(), chain_name);
```

**Comment by mattsse** [comment]
this is done in the `display` impl

https://github.com/gakonst/ethers-rs/blob/b07b3024107e4dc81be285a684974afd5b3c568b/ethers-core/src/types/chain.rs#L41-L45

which by default prints the Variant name, 
simply inversing the `FromStr` match would be better

Do you want to take this on? Basically switching left and right arm of this match

https://github.com/gakonst/ethers-rs/blob/b07b3024107e4dc81be285a684974afd5b3c568b/ethers-core/src/types/chain.rs#L98-L120
