### ISSUE TITLE
Problem: compiling issue on windows

### ISSUE THREAD

**Issue by leejw51crypto** [gakonst/ethers-rs#902]
0.6.2 from crates.io , is not compiled in windows ,
by assembly issue

but when i use main branch from github directly, it's OK in windows.
could you update crates.io to use latest main branch?

**Comment by gakonst** [comment]
Yep need to do a new release, do you mind using the latest branch for now?

**Comment by leejw51crypto** [comment]
yes, i'm using from master branch, working fine on windows

**Comment by chubei** [comment]
> ok, i'm using from master branch, working fine on windows

Hi, which commit id you're using? I can't find a one that works for me.
