### ISSUE TITLE
Strip trailing /contracts from autodetected remappings inside node_modules folder

### ISSUE THREAD

**Issue by mattsse** [gakonst/ethers-rs#906]
rn `contracts` and `src` are treated somewhat equally.
however dapptools style (`src`) usually skips over `src` while hardhat style includes `contracts` in the import paths.

when auto detecting remappings the trailing /contracts should be removed to make auto remappings work out of the box in existing hardhat repos.

**Comment by gakonst** [comment]
Yeah also wonder if we should hardcode the popular packages in the code, e.g. `@openzeppelin` instead of `openzeppelin-conrtacts`? Is there some way for us to automatically detect that? Probably not
