### ISSUE TITLE
String/fragment based Interface/ABI support

### ISSUE THREAD

**Issue by SilentCicero** [gakonst/ethers-rs#95]
Heyo,

Killing it Georgios.

Is there the Interface/String based ABI decoder in `ethers.rs`.

I'd like to describe contract ABI that way, ie:
```
[ "function someMethod() returns (uint256)", "function ..." ]
```

**Comment by vaibhavchellani** [comment]
Think there is something in works here: https://github.com/gakonst/ethers-rs/pull/88

**Comment by roynalnaruto** [comment]
@SilentCicero You can check an example usage [here](https://github.com/gakonst/ethers-rs/blob/master/ethers/examples/contract.rs#L8-L18)

**Comment by gakonst** [comment]
Also here: https://github.com/gakonst/ethers-rs/blob/master/ethers-core/src/abi/human_readable.rs#L16

**Comment by SilentCicero** [comment]
Very cool. This is great, basically Ethers but in Rust. Can it get any better? Closing.
