### ISSUE TITLE
abigen: missing field abi

### ISSUE THREAD

**Issue by jeprojects** [gakonst/ethers-rs#960]
When using the example code, abigen throws and error:

`missing field 'abi' at line 1 column 108`

code:

```
[dependencies]
ethers = { version = "0.6.2", features = ["abigen"] }

abigen!(
    MyContract, "etherscan:0xdAC17F958D2ee523a2206206994597C13D831ec7";
    MyContract2, "etherscan:0x8418bb725b3ac45ec8fff3791dd8b4e0480cc2a2";
);
```

Update: Updated abigen!

**Comment by jeprojects** [comment]
@mattsse  @gakonst I noticed my code above was using an address that didn't have a contract, which is from your docs.

I have already tried with an address with a verified contract and the same error occurs.

**Comment by jeprojects** [comment]
@mattsse @gakonst Updates the macro.

IntelliJ lint is still giving the error but always fails for MyContract2

**Comment by mattsse** [comment]
@jeprojects couldn't reproduce as #964 compiles successfully

**Comment by jeprojects** [comment]
@mattsse Thanks for the help.

Master on GitHub has a dependency version conflict

```
[dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs" }
```

`failed to select a version for 'base64ct' which could resolve this conflict`

`error: failed to select a version for 'base64ct'.`

**Comment by gakonst** [comment]
We have [this](https://github.com/gakonst/ethers-rs/blob/master/Cargo.lock#L173-L175), can you share how you get this conflict? maybe it's some other dependency of yours?

```
[package]]
name = "base64ct"
version = "1.0.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "8a32fd6af2b5827bce66c29053ba0e7c42b9dcab01835835058558c10851a46b"
```

**Comment by jeprojects** [comment]
Looks like it was an issue on my end. 

`cargo clean` didn't resolve it and had to delete `Cargo.lock` manually

However, using the github version I am still getting the abi issue.

```
abigen!(
    MyContract, "etherscan:0xdAC17F958D2ee523a2206206994597C13D831ec7";
    MyContract2, "etherscan:0x8418bb725b3ac45ec8fff3791dd8b4e0480cc2a2";
);
```


```
error: missing field `abi` at line 1 column 108
 --> src/main.rs:7:17
  |
7 |     MyContract, "etherscan:0xdAC17F958D2ee523a2206206994597C13D831ec7";
  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jeprojects** [comment]
Tried without using the macro and still the same error:

```
Abigen::new("ABITEST", "etherscan:0xdAC17F958D2ee523a2206206994597C13D831ec7")
        .unwrap()
        .generate()
        .unwrap();
```

`thread 'main' panicked at 'called 'Result::unwrap()' on an 'Err' value: missing field 'abi' at line 1 column 108`

**Comment by mattsse** [comment]
what's the ethers version in your lockfile?

**Comment by jeprojects** [comment]
```
[[package]]
name = "ethers"
version = "0.6.0"
source = "git+https://github.com/gakonst/ethers-rs#b6c22e9bccdad5c015f04e89bc808f441ffb5ec9"
dependencies = [
 "ethers-addressbook",
 "ethers-contract",
 "ethers-core",
 "ethers-etherscan",
 "ethers-middleware",
 "ethers-providers",
 "ethers-signers",
 "ethers-solc",
]
```

**Comment by jeprojects** [comment]
Do you think that etherscan has some kind of rate-limiting? Maybe it's receiving a blank file and throwing that error?

It seems to randomly fail. First attempt always fails to compile, second most of the time works for single abi's only.

If I use multiple, it will never compile as one will usually fail with the error `error: missing field `abi` at line 1 column 108`

**Comment by jeprojects** [comment]
Yes the error is related to etherscans rate-limiting.

After adding an API key, everything works fine.

Perhaps ethers-rs need to handle this error:

```
{"status":"0","message":"NOTOK","result":"Max rate limit reached, please use API Key for higher rate limit"}
```

**Comment by mattsse** [comment]
thanks for this, Added a better error message here #971
you'd need to set the `ETHERSCAN_API_KEY` env var to not get rate limited like this, that's why we didn't catch it earlier because we're using ETHERSCAN_API_KEY in ci
