### ISSUE TITLE
Suggestion: use PrehashSignature::Digest and remove Sha256Proxy

### ISSUE THREAD

**Issue by tmpfs** [gakonst/ethers-rs#966]
I think it is possible to remove the `Sha256Proxy` code in the signers crate because `recoverable::Signature` implements the `PrehashedSignature` trait which sets the `Digest` to `Keccak256`:

https://docs.rs/k256/latest/k256/ecdsa/recoverable/struct.Signature.html#impl-PrehashSignature

You would then not need to call `tx.sighash()` just `tx.rlp()` instead and let `k256` perform the hashing by calling `sign()` instead of `sign_digest()` then the `Sha256Proxy` code could be removed.

Of course there may be some subtle issue that prevents this I am not aware of 🙏

**Comment by gakonst** [comment]
Closing as discussed in the PR I am not sure this is actually doable. I pinged @bascule as well just in case about it to confirm

**Comment by tarcieri** [comment]
If you'd like to get rid of `Sha256Proxy`, I'd suggest using the low-level `ecdsa::hazmat::SignPrimitive` interface:

There are a couple code examples here:

- https://github.com/RustCrypto/elliptic-curves/issues/528#issuecomment-1054525817
- https://github.com/RustCrypto/elliptic-curves/issues/525#issuecomment-1044792388
