### ISSUE TITLE
Stream events, including past ones

### ISSUE THREAD

**Issue by palango** [gakonst/ethers-rs#988]
**Is your feature request related to a problem? Please describe.**

Currently there are two ways to query events:
- with a filter for a given range:`contract.events().from_block(block_number).query().await`. This allows to query events that have been emitted in the past.
- streaming new events: `contract.events().stream().await`. This will only yield events that are emitted after the stream has been created.

**Describe the solution you'd like**
Ideally, there would be a way to get a stream of events from a given point in the past. I.e. a function that combines both above functions.

**Additional context**
See https://github.com/gakonst/ethers-rs/issues/986

**Comment by mattsse** [comment]
I see, so `contract.events().from_block(block_number).query().await` should turn into `contract.events().stream().await` once the head is reached?

So I guess we should make this the default behaviour if no `end_block` was set

**Comment by gakonst** [comment]
@meetmangukiya wanna go for this?

**Comment by FancyRatsDave** [comment]
Still the case for `abigen!` `Contract` types?

```
    let pool_contract = LendingPool::new(lending_pool, client.clone());
    let last_block = client.get_block(BlockNumber::Latest).await?.unwrap().number.unwrap();
    let events = pool_contract.events();
    let filtered = events.from_block(last_block - 10000);
    let mut stream = filtered.stream().await?;
    while let Some(log) = stream.next().await {
        println!("{:?}", &log);
    }
```

Only get past events if I use 
```
    let last_block = client.get_block(BlockNumber::Latest).await?.unwrap().number.unwrap();
    let events = pool_contract.events();
    let result = events.from_block(last_block - 1000).query().await?;
    println!("{:?}", &result);
```

Perhaps I'm screwing it up?

**Comment by gakonst** [comment]
I believe we don't do that in abigen. Let's track in a separate issue. Or feel free to add!

**Comment by Mirko-von-Leipzig** [comment]
Its not quite clear to me what is supported for this and what is not.

1. Are only web-sockets supported? Or does this work with the filter polling on http as well?
2. Abigen contracts won't work? So one needs to use the provider functions and lose the type safety?
3. From the PR code I think you have a race condition. If there is a reorg or another new block between your last query and your subscription, then you'll miss it. Unless this is handled elsewhere?

**Comment by Bridgerz** [comment]
@Mirko-von-Leipzig did anything ever come of this? Attempting to write an indexer using ethers-rs events.

**Comment by Mirko-von-Leipzig** [comment]
> @Mirko-von-Leipzig did anything ever come of this? Attempting to write an indexer using ethers-rs events.

Not afaik - we ended up doing this using normal HTTP RPC methods with overlapping block ranges to guard against reorgs.
